umee-network/umee

app/app.go
cmd/umeed/cmd/root.go
go.mod
go.sum

cli: use gravity gentx commands

---

Dockerfile
app/app.go
go.mod
go.sum
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/e2e_util_test.go

chore: bump SDK and Gravity

---

tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/e2e_util_test.go
tests/e2e/eth_abi.go

- Use geth `abi`pkg.
- Use a single eth client instance.
----
I have...
I have...

chore: e2e updates

---

cmd/umeed/cmd/root.go

Add support for the vanilla gentx command to be used with Starport and local network testing where gravity isn't required.
----
I have...
I have...

chore: add vanilla gentx cmd

---

.github/CODEOWNERS
app/app.go
tests/e2e/e2e_test.go
tests/e2e/e2e_util_test.go

closes: #39
closes: #12
----
I have...
I have...

feat: Enable the x/authz and x/feegrant

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
CHANGELOG.md
Makefile

Setup go release.
closes: #20
----
I have...
I have...

feat: setup goreleaser

---

CHANGELOG.md

chore: add changelog from v0.1.0

---

README.md
networks/umee-betanet-1/genesis.json

chore: betanet updates

---

go.mod
go.sum

chore: bump IBC version

---

Dockerfile
go.mod
go.sum

Update Cosmos SDK to 0.44 and Gravity Bridge to 0.2.0.
closes #73
closes #76
----
I have...
I have...

build(deps): Update Cosmos SDK to 0.44 and Gravity Bridge to 0.2.0 (#73 and #76)

---

.github/CODEOWNERS

chore: Add toteki to CODEOWNERS

---

Dockerfile
go.mod
go.sum

Bump gravity bridge to v0.2.7
----
I have...
I have...

chore: bump gravity bridge version

---

.github/workflows/lint.yml
.markdownlint.yml
README.md

Add super-linter to CI to enable markdown linting.
closes: #102 
----
I have...
I have...

chore: add super-linter to CI

---

README.md
networks/umee-betanet-2/genesis.json

chore: update to betanet-2

---

.golangci.yml
x/leverage/keeper/msg_server.go
x/leverage/types/events.go

- Flesh out the message server
- Add events and logging
----
I have...
I have...

chore: x/leverage: msg server updates

---

docs/architecture/ADR-002-deposit-assets.md

Updates message names (`MsgDeposit` -> `MsgLendAsset`) and other minor details in ADR-002 to reflect current implementation
----
I have...
I have...

docs: ADR-002 housekeeping

---

app/modules.go

Fix metadata so Peggy transfers will work.
----
I have...
I have...

fix: fix bank metadata

---

starport.ci.yml
x/peggy/client/cli/query.go

Add ERC20 mapping query CLI commands to the x/peggy module.
----
I have...
I have...

feat: x/peggy ERC20 mapping CLI queries

---

x/oracle/keeper.go
x/oracle/types/asset.go
x/oracle/types/keys.go

Add functions on the keeper for oracle.
----
I have...
I have...

feat: Add keeper functions for oracle

---

x/oracle/ballot.go
x/oracle/slash.go

Add slashing functionality when a validator acts nefariously.
closes: #XXXX
----
I have...
I have...

feat: Add slashing functions to oracle

---

x/peggy/client/cli/query.go
x/peggy/client/cli/tx.go
x/peggy/client/tests/suite.go
x/peggy/types/msgs.go

- Add some tests
- Cleanup
----
I have...
I have...

chore: cleanup x/peggy CLI

---

.github/CODEOWNERS
x/leverage/gov_handler.go
x/leverage/gov_handler_test.go
x/leverage/keeper/token.go
x/oracle/ballot.go
x/oracle/keeper.go

- Ensure we remove all registered tokens prior to updating them via governance
- some x/oracle cleanup
----
I have...
I have...

fix: update registered tokens correctly on proposal

---

.github/PULL_REQUEST_TEMPLATE.md

Add "add appropriate labels to PR" item to pull request template
----
I have...
I have...

chore: PR checklist += add PR labels

---

Makefile
go.sum
tests/e2e/docker/hermes.Dockerfile
tests/e2e/e2e_test.go
tests/e2e/scripts/hermes_bootstrap.sh

ref: https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md#v090-the-zamfir-release
----
I have...
I have...

chore: update ibc-rs version in e2e tests

---

go.sum
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/binance_test.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/kraken_test.go
price-feeder/oracle/provider/provider.go
price-feeder/oracle/util.go
price-feeder/oracle/util_test.go

closes: #251 
----
I have...
I have...

refactor: Price Feeder VWAP 

---

x/leverage/keeper/keeper_test.go
x/leverage/keeper/token.go
x/leverage/types/keys.go

Simplify token and utoken denom allow-list logic using token registry and types.UTokenPrefix
----
I have...
I have...

refactor: token and uToken allow lists

---

x/oracle/client/cli/query.go
x/oracle/client/cli/tx.go
x/oracle/genesis.go
x/oracle/keeper/alias_functions.go
x/oracle/keeper/grpc_query.go
x/oracle/keeper/msg_server.go
x/oracle/keeper/params.go
x/oracle/keeper/reward.go
x/oracle/keeper/slash.go

chore: x/oracle housekeeping

---

x/oracle/types/ballot.go
x/oracle/types/ballot_test.go

chore: remove cross rate from x/oracle

---

price-feeder/oracle/oracle.go

Keeps the price feeder running if `o.tick()` returns with an error 
----
I have...
I have...

refactor: don't shut down the price feeder on errors

---

price-feeder/go.mod
price-feeder/go.sum
price-feeder/oracle/client/client.go
price-feeder/oracle/oracle.go

chore: price-feeder tweaks

---

x/oracle/keeper/keeper.go
x/oracle/keeper/keeper_test.go

Normalizes exchange rates when setting and querying
closes: #305
----
I have...
I have...

refactor: normalize exchange rates 

---

x/oracle/abci.go

Cleanup the Tally method slightly.
----
I have...
I have...

chore: x/oracle tally cleanup

---

price-feeder/config/config.go
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/mock.go
price-feeder/oracle/provider/mock_test.go
starport.ci.beta.yml

Add support for a mock provider using Google Sheets as a backend. This allows us to test the Umee application without having to rely on a real provider, so we can fetch prices for umee, etc...
Google Sheet: https://docs.google.com/spreadsheets/d/1wdaXPwlTqWnwhco4KQGEK5M0tXjCRQ1X4D-dIEiI1Xc/edit#gid=0
----
I have...
I have...

feat: mock provider

---

x/leverage/client/cli/tx.go

Adds CLI command for `MsgLiquidate`
Progress toward #94 
----
I have...
I have...

feat: Liquidate command

---

x/oracle/keeper/keeper.go
x/oracle/types/asset.go

fix USD check
----
I have...
I have...

fix: x/oracle USD check

---

price-feeder/config/config.go
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/huobi_test.go

feat: price-feeder - add huobi provider

---

price-feeder/config/config.go
price-feeder/oracle/oracle.go
price-feeder/oracle/oracle_test.go
price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/binance_test.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/huobi_test.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/kraken_test.go
price-feeder/oracle/provider/mock.go
price-feeder/oracle/provider/mock_test.go
price-feeder/oracle/provider/osmosis.go
price-feeder/oracle/provider/osmosis_test.go
price-feeder/oracle/provider/provider.go
price-feeder/oracle/types/currency.go

- add support for an osmosis provider
- refactor the provider interface a bit
----
I have...
I have...

feat: price-feeder - osmosis provider support

---

docs/architecture/ADR-001-interest-stream.md
docs/architecture/ADR-002-deposit-assets.md
docs/architecture/ADR-003-borrow-assets.md
docs/architecture/ADR-004-interest-and-reserves.md
docs/architecture/ADR-005-liquidation.md
docs/architecture/ADR-007-bad-debt.md
docs/architecture/README.md

- Check for misspelled stuff in the `docs/architecture` path
----
I have...
I have...

chore: Misspell check on ADR

---

price-feeder/README.md
price-feeder/config/config.go
price-feeder/config/config_test.go
price-feeder/price-feeder.example.toml
tests/e2e/scripts/price_feeder_bootstrap.sh

closes: #XXXX
----
I have...
I have...

chore: price-feeder readme

---

app/beta/app.go

This can be automerged - additional work is in a separate PR.
----
I have...
I have...

fix: nil oracle keeper in beta app

---

app/beta/test_helpers.go
x/oracle/client/tests/suite.go

- add a mock exchange rate for umee
- add a large voting period to clear our exchange rates (since we're not submitting votes)
- add tests to oracle CLI
----
I have...
I have...

refactor: update genesis state CLI integration tests

---

app/app.go
app/beta/app.go
app/beta/test_helpers.go
x/leverage/client/tests/suite.go
x/leverage/client/tests/util.go
x/leverage/types/codec.go

Add an auxiliary method that does automatic registry update governance proposal submission, voting and waiting till proposal is complete.
E.g.
```go
val := s.network.Validators[0]
s.UpdateRegistry(
val.ClientCtx,
types.NewUpdateRegistryProposal(
"test title",
"test description",
[]types.Token{
{
BaseDenom:            app.BondDenom,
SymbolDenom:          app.DisplayDenom,
Exponent:             6,
ReserveFactor:        sdk.MustNewDecFromStr("0.200000000000000000"),
CollateralWeight:     sdk.MustNewDecFromStr("0.070000000000000000"),
BaseBorrowRate:       sdk.MustNewDecFromStr("0.040000000000000000"),
KinkBorrowRate:       sdk.MustNewDecFromStr("0.400000000000000000"),
MaxBorrowRate:        sdk.MustNewDecFromStr("1.60000000000000000"),
KinkUtilizationRate: …
```

feat: cli integration tests - registry update helper

---

price-feeder/oracle/oracle.go

Adds a warning message for any denoms in our accept list that a price feeder isn't submitting votes for 
closes: #361
----
I have...
I have...

feat: price-feeder: add warning message for missing denoms

---

app/app.go
app/beta/app.go
tests/e2e/e2e_setup_test.go
x/oracle/client/tests/suite.go
x/oracle/keeper/grpc_query_test.go
x/oracle/keeper/hook_test.go
x/oracle/keeper/keeper_test.go

chore: app tweaks

---

Dockerfile

chore: e2e tests - bump peggo

---

x/leverage/client/tests/suite.go
x/leverage/keeper/collateral.go
x/leverage/keeper/interest.go
x/leverage/keeper/keeper_test.go
x/leverage/types/keys.go
x/leverage/types/keys_test.go

-  Implemented function to get the list of borrower addresses eligible for liquidation.
ref: #229  
----
I have...
I have...

feat: List the Borrower Addr Eligible for Liquidation

---

x/leverage/keeper/borrows.go
x/leverage/keeper/exchange_rate.go
x/leverage/keeper/interest.go
x/leverage/keeper/lend.go

Switched to a panic because the only error condition is bad encoding.
----
I have...
I have...

refactor: remove k.GetTotalBorrows error return

---

x/leverage/types/expected_types.go

Removes a now-outdated comment
----
I have...
I have...

chore: remove old BankKeeper comment

---

price-feeder/oracle/client/client.go

Removes an unnecessary err check
----
I have...
I have...

chore: price-feeder: remove unnecessary err check 

---

go.mod
go.sum

Updated Gravity Bridge module
https://github.com/Gravity-Bridge/Gravity-Bridge/releases/tag/v1.3.3
Commit: 90cc0c9bb07fd9e92464bfdf80876893e9fc074d
----
I have...
I have...

chore: Update Gravity Bridge to v1.3.3

---

x/leverage/keeper/keeper.go

closes: #417
----
I have...
I have...

chore: remove unused variable reassignment in Liquidate

---

infra/packer/umee-node-dist.pkr.hcl

Bug fix for #428 
I have...
I have...

build: set exit code every time instead of only on failure for bash loop 

---

infra/packer/umee-node-dist.pkr.hcl
tests/e2e/docker/hermes.Dockerfile

https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md#v0110
I have...
I have...

chore: update hermes to 0.11

---

x/oracle/keeper/keeper.go
x/oracle/keeper/keeper_test.go

- Removed duplicated error check
- Add unit test to check for errors
ref #455
----
I have...
I have...

refactor: removed duplicated error check

---

x/oracle/keeper/reward.go

- Add continue to for loop when the validator is nil or when there is no reward coins
ref #455
----
I have...
I have...

refactor: continue looping when Validator is nil

---

.github/workflows/publish-images.yml

target 'release/**' in addition to main for image builds

chore: also target release branches for packer image build

---

infra/packer/Dockerfile.build

chore: bump peggo to v0.2.2

---

x/oracle/types/msgs.go

fix: oracle msg GetSigners should not panic on err

---

x/oracle/spec/01_concepts.md

Updates the x/oracle spec to include what happens if there are zero coins in the oracle reward pool.
closes: #452
----
I have...
I have...

fix: update oracle spec to clarify zero rewards

---

.github/workflows/publish-images.yml

fix: image job not running because conditional logic is wrong

---

.github/workflows/publish-images.yml

Github Actions is missing conditional logic to enable release building...

fix: image job not running for release  because conditional logic is wrong

---

x/oracle/keeper/keeper.go
x/oracle/keeper/msg_server.go

Just makes the check for existing prevotes more readable 
----
I have...
I have...

chore: clean up existing prevote logic 

---

app/app.go
app/beta/app.go

This adds the proposal handler for the Gravity Bridge module.
closes: #476
----
I have...
I have...

fix: Add gravity proposal handler

---

Dockerfile

chore: update peggo version in e2e tests

---

x/leverage/keeper/keeper.go

closes: #507
----
I have...
I have...

fix: possible divisions by zero in LiquidateBorrow

---

.mergify.yml

chore: prep v1

---

CHANGELOG.md
Makefile

- Fix makefile `build` and `install` targets to support Ledger devices.
----
I have...
I have...

fix: enable ledger support

---

Dockerfile

closes: #523
----
I have...
I have...

fix: fix e2e test failures

---

Dockerfile

Tested locally
closes: #523
----
I have...
I have...

fix: e2e tests

---

x/leverage/types/params.go

closes: #512
----
I have...
I have...

fix: prevent complete liquidation threshold = 0

---

x/leverage/spec/01_concepts.md

Adds warning in the leverage spec's `01_concepts.md` document that lending assets or enabling collateral while eligible for liquidation, if the new collateral amount is not enough to restore borrow health, risks the newly lent/enabled collateral for liquidation.
closes: #514
----
I have...
I have...

docs: update leverage spec

---

price-feeder/CHANGELOG.md

Adds the okx provider PR to our changelog 
----
I have...
I have...

docs: price-feeder: add okx PR to the changelog

---

price-feeder/CHANGELOG.md
price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/okx.go

- Cleaned up logs from the following price feeders providers:
-  Binance
- Huobi
- Kraken
- Okx
closes: #581 
----
I have...
I have...

chore: price-feeder: clean up logs

---

ante/fee.go
ante/spam_prevention.go

Most of this was taken from Terra's code and the godocs were not that great.
----
I have...
I have...

chore: cleanup custom ante-handler godocs

---

price-feeder/CHANGELOG.md
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/provider.go
price-feeder/oracle/util.go
price-feeder/oracle/util_test.go

Adds faulty provider detection logic for tvwap. Also includes some cleanup on the StandardDeviation method & a couple type aliases to make code easier to read. 
progress on: #542
----
I have...
I have...

feat: faulty provider detection for tvwap

---

price-feeder/oracle/oracle.go

Add an error message on pairs for which we could not get candles.
closes: #619
----
I have...
I have...

feat: price-feeder: add missing candles warning

---

price-feeder/CHANGELOG.md

The changelog should be updated each time we cut a release 👍 
----
I have...
I have...

docs: price-feeder: clean up the changelog

---

price-feeder/CHANGELOG.md

Adds v0.1.4 to the price feeder changelog
----
I have...
I have...

docs: update price-feeder changelog

---

README.md

docs: update readme for v2

---

.mergify.yml

ci: add backport workflow for 2.x.x

---

networks/umee-1/README.md

closes: #XXXX
----
I have...
I have...

docs: Add state sync service

---

CHANGELOG.md

Adds 2.0.0 to the changelog so that we can start updating it regularly for 2.x.x :)
----
I have...
I have...

docs: changelog update

---

README.md
networks/umee-1/README.md

closes: #XXXX
----
I have...
I have...

docs: readme cleanup

---

price-feeder/README.md

closes: #XXXX
----
I have...
I have...

docs: price-feeder: readme cleanup

---

price-feeder/CHANGELOG.md
price-feeder/oracle/provider/mock.go

References a new google doc which has some randomness in it 
----
I have...
I have...

feat: add randomness to mock provider

---

.github/workflows/price-feeder-release.yml
price-feeder/.goreleaser.yml

closes: #XXXX
----
I have...
I have...

ci: remove release notes from price feeder goreleaser

---

CHANGELOG.md

Updates the v2 changelog
----
I have...
I have...

docs: changelog++

---

price-feeder/CHANGELOG.md

Price feeder changelog update 😄 
----
I have...
I have...

docs: price-feeder changelog update

---

price-feeder/CHANGELOG.md

Adds the 0.2.1 release to the price feeder changelog
----
I have...
I have...

docs: price-feeder v0.2.1 changelog update

---

networks/umee-1/README.md

add state sync and snapshots porviders
closes: #XXXX
----
I have...
I have...

docs: add bitszn state sync and snapshot provider info

---

networks/umeemania-1/genesis.json

Just adding the umeemania genesis file here in case other validators want to join the testnet :^) 
----
I have...
I have...

chore: add umeemania genesis file

---

CHANGELOG.md

chore: changelog++

---

networks/umee-1/README.md

feat: snapshot, rpc, api services added
docs: web page link changed
closes: #XXXX
----
I have...
I have...

chore: update state sync providers

---

CHANGELOG.md
app/app.go

Adds the update-client proposal handler as well as the IBC update proposal handler. Both are critical for managing IBC connections. Specifically, update-client unfreezes stuck client connections and, as a consequence, stuck tokens.
app.go has 3 changed lines that add these features.
closes: #859 
----
I have...
I have...

feat: added update-clent and IBC update proposals

---

CHANGELOG.md

Changelog update
----
I have...
I have...

chore: cl++

---

CONTRIBUTING.md
README.md

+ Adds information about release model
+ Updates contributing instructions.
closes: #879
----
I have...
I have...

chore: update release procedure

---

CONTRIBUTING.md

Just clarifies when our semver policy started
----
I have...
I have...

docs: contributing.md clarification

---

docs/architecture/ADR-006-oracle.md
price-feeder/README.md

Updates references to terra's oracle to the renamed [classic-core
](https://github.com/terra-money/classic-core) repo
----
I have...
I have...

docs: update terra references to classic

---

CHANGELOG.md
x/leverage/keeper/interest.go

Tiny audit issue fix
closes: #867

chore: streamline AccrueAllInterest

---

CHANGELOG.md
x/leverage/keeper/keeper.go

Tiny audit issue fix
closes: #896
closes: #868

chore: improve ModuleBalance

---

CHANGELOG.md
x/leverage/keeper/interest.go
x/leverage/keeper/math.go

Makes interest accrual math more accurate.
closes: #942 
----
I have...
I have...

fix: taylor series of exponential used for interest accrual

---

contrib/scripts/protocgen.sh

chore: clean protocgen.sh

---

price-feeder/.goreleaser.yml

Last bit of #968
----
I have...
I have...

chore: update price feeder releaser to use 1.18

---

networks/umee-1/README.md

closes: #XXXX
----
I have...
I have...

docs: Add snapshot service from sourled

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

As discussed during the call: updated PR templates.
----
I have...
I have...

chore: updated github templates

---

CHANGELOG.md

chore: add missing changelog for #1023

---

price-feeder/CHANGELOG.md
price-feeder/oracle/oracle.go
price-feeder/oracle/oracle_test.go
price-feeder/oracle/param.go
price-feeder/oracle/param_test.go

- Add cache for [price feeder](https://github.com/umee-network/umee/blob/e13cb3e9939e6903b9ba2cadbd9ea21f5217fb7c/price-feeder/oracle/oracle.go#L282) `o.GetParams` for 200 blocks (hardcoded)
closes: #1049 
---
I have...
I have...

feat!: cache get params for 200 blocks

---

price-feeder/.goreleaser.yml

- Fix go releaser
---
I have...
I have...

fix: gorelease from 1.18 compat to 1.17

---

x/leverage/client/cli/query.go
x/leverage/client/cli/tx.go
x/oracle/client/cli/tx.go

Updates client comments for accuracy per @robert-zaremba's [comment](https://github.com/umee-network/umee/pull/1029#discussion_r909430454)

chore: update CLI comments in oracle and leverage modules

---

price-feeder/CHANGELOG.md

Price feeder changelog updates
---
I have...
I have...

chore: price-feeder changelog

---

price-feeder/CHANGELOG.md
price-feeder/oracle/client/chain_height.go
price-feeder/oracle/client/client.go

Just small cleanup around the price-feeder height subscription logic
---
I have...
I have...

fix: price-feeder height subscription cleanup

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/simulations.yml
.github/workflows/tests.yml

Optimizes github workflows
---
I have...
I have...

chore: optimize build workflow

---

price-feeder/CHANGELOG.md

Adds the latest price feeder release to our changelog
---
I have...
I have...

chore: price-feeder changelog update

---

CHANGELOG.md
price-feeder/cmd/price-feeder.go
price-feeder/oracle/oracle.go
tests/e2e/e2e_setup_test.go
x/oracle/client/cli/query.go

closes: #1155
---
I have...
I have...

fix: propagate context

---

price-feeder/cmd/version.go
price-feeder/go.mod

Different version of yaml was specified in go.mod and different was imported
---
I have...
I have...

fix: sync yaml version

---

price-feeder/CHANGELOG.md
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/binance_test.go
price-feeder/oracle/provider/coinbase.go
price-feeder/oracle/provider/coinbase_test.go
price-feeder/oracle/provider/gate.go
price-feeder/oracle/provider/gate_test.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/huobi_test.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/kraken_test.go
price-feeder/oracle/provider/okx.go
price-feeder/oracle/provider/okx_test.go

Improves some provider logs for when we can't find prices for given providers
---
I have...
I have...

chore(price-feeder): improve provider logs

---

price-feeder/CHANGELOG.md

chore: pfcl++

---

Makefile
proto/buf.gen.gogo.yaml
x/leverage/types/leverage.pb.go
x/leverage/types/query.pb.gw.go
x/oracle/types/query.pb.gw.go

We didn't separate proto images, and were missing option for grpc-web.
---
I have...
I have...

fix: add missing grpc-web and set the project name

---

price-feeder/oracle/provider/binance_test.go
price-feeder/oracle/provider/coinbase_test.go
price-feeder/oracle/provider/gate_test.go
price-feeder/oracle/provider/huobi_test.go
price-feeder/oracle/provider/kraken_test.go
price-feeder/oracle/provider/okx_test.go
x/oracle/keeper/reward.go

Use `require.ErrorEqual`
---
I have...
I have...

chore: improve assertion style

---

CHANGELOG.md
x/oracle/client/cli/tx.go

Necessary for use with our https://github.com/umee-network/qa-integration/ suite 
---
I have...
I have...

feat(oracle): cli commands for prevoting / voting

---

.github/workflows/build.yml
.github/workflows/debug.yml
.github/workflows/lint.yml
.github/workflows/price-feeder-release.yml
.github/workflows/proto.yml
.github/workflows/release.yml
.github/workflows/simulations.yml
.github/workflows/tests.yml
.golangci.yml
Makefile
ante/spam_prevention.go
cmd/umeed/cmd/debug.go
cmd/umeed/cmd/genaccounts.go
cmd/umeed/cmd/root.go
go.mod
price-feeder/oracle/oracle.go
util/checkers/sign.go
x/leverage/client/cli/proposal.go
x/leverage/keeper/keeper.go
x/leverage/keeper/liquidate.go
x/oracle/abci.go
x/oracle/simulations/operations.go
x/oracle/types/errors.go

While working on the cosmos-v046 branch, I found that our golangci-lint is not working correctly. Here is the fix.
---
I have...
I have...

chore(ci): update github lint and cache workflow

---

price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/coinbase.go
price-feeder/oracle/provider/gate.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/okx.go
price-feeder/oracle/types/errors.go
x/oracle/types/errors.go

- additionally handles okx & kraken
closes: #1192 
---
I have...
- [ x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ x ] reviewed "Files changed" and left comments if necessary
- [ x ] confirmed all CI checks have passed
I have...
- [ x ] confirmed the correct [type …

fix: HAL-05 Unhandled Errors

---

price-feeder/CHANGELOG.md
price-feeder/oracle/convert.go

- Reduce scope of 046 branch #1217 
- Avoids panic in cases where it doesn't find a conversion rate for the quote 
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5299a8]
goroutine 77 [running]:
math/big.(*Int).Mul(0xc001b78360, 0xc001b78360, 0x0)
/usr/local/go/src/math/big/int.go:167 +0xa8
[github.com/cosmos/cosmos-sdk/types.Dec.MulMut({0xffffffffffffffff?}](http://github.com/cosmos/cosmos-sdk/types.Dec.MulMut(%7B0xffffffffffffffff?}), {0x0?})
/home/rafilx/go/pkg/mod/github.com/umee-network/cosmos-sdk@v0.46.0-umee.0.20220812010629-4d5bb2e3f73c/types/decimal.go:289 +0x28
[github.com/cosmos/cosmos-sdk/types.Dec.ImmutOp({0x19dc500?}](http://github.com/cosmos/cosmos-sdk/types.Dec.ImmutOp(%7B0x19dc5 …
```

fix: add verification to conversionRates

---

price-feeder/router/v1/response.go
price-feeder/router/v1/router.go

- when returning data back during an HTTP response
- since we can trust `json.Marshal`, let's just check the error case
closes: #XXXX
---
I have...
I have...

chore: WIP HAL-07 use the html/template package #1195

---

.github/workflows/dependencies-review.yml

Adding dependency review check to Github Workflow.
This action scans your pull requests for dependency changes and will raise an error if any new dependencies have existing vulnerabilities. The action is supported by an [API endpoint](https://docs.github.com/en/rest/reference/dependency-graph#dependency-review) that diffs the dependencies between any two revisions.
---
I have...
I have...

feat(ci): add dependencies review check

---

.github/workflows/linkchecker.yml

Check if links in markdown diff are valid.
---
I have...
I have...

feat(ci): add markdown link checker

---

.github/workflows/proto.yml

Use filepath filter for workflow event to not even start a workflow if it's not needed.
---
I have...
I have...

chore(ci): add event file filters to workflows

---

.github/workflows/codeql-analysis.yml

Adds crypto.com codeql check to analyze security issues.
---
I have...
I have...

feat(ci): add codeql checks

---

.github/workflows/linkchecker.yml
docs/design_docs/001-interest-stream.md
docs/design_docs/006-oracle.md
networks/umee-1/README.md
price-feeder/CHANGELOG.md
price-feeder/README.md

- can set `VALIDATE_MARKDOWN: false` in .github/workflows/main.yml to disable markdown linting completely
closes: #XXXX
---
I have...
- [ x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x ] added `!` to the type prefix if API or client breaking change
- [ x ] added appropriate labels to the PR
- [ x ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ x ] provided a link to the relevant issue or specification
- [ x ] included comments for [documenting Go …

chore: disable linting for all link-related checks

---

price-feeder/oracle/provider/osmosis.go

Fixes golint issue.
---
I have...
I have...

fix: use http.Status* codes

---

.github/workflows/lint.yml

Some diff patterns were not properly set - this caused lint CI job to fail.
---
I have...
I have...

ci: github workflow diff patterns

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/debug.yml
.github/workflows/lint.yml
.github/workflows/price-feeder-release.yml
.github/workflows/release.yml
.github/workflows/simulations.yml
.github/workflows/tests.yml
.goreleaser.yml
contrib/scripts/go-mod-tidy-all.sh
go.mod
price-feeder/go.mod
tests/e2e/docker/gaia.Dockerfile
umee.e2e.Dockerfile

Move our setup to go1.19
Related to: https://github.com/umee-network/umee/issues/1260
---
I have...
I have...

chore: go 1.19

---

app/modules.go

Allow gentx to not contain Ethereum contract registration.
---
I have...
I have...

feat: less strict gentx validator

---

.github/workflows/tests.yml
.gitignore
contrib/scripts/single-node.sh
contrib/scripts/test_localnet_liveness.sh

helps: #1265
---
I have...
I have...

fix: single node script with liveness

---

price-feeder/price-feeder.example.toml

Updates the price-feeder's example config with options in preparation for mainnet.
Locally I don't see any errors, please double check me 😄 
closes: #1270
---
I have...
I have...

chore(price-feeder): update example config

---

.mergify.yml
price-feeder/CHANGELOG.md

Changelog & mergify updates for the price feeder release
---
I have...
I have...

chore(price-feeder): mergify & changelog updates

---

x/oracle/client/cli/tx.go

Fixes a problem I introduced in #1323 😢 
---
I have...
I have...

fix(cli): use the correct ValAddress function for votes & prevote delegations

---

price-feeder/price-feeder.example.toml

Updates the example price-feeder config to properly turn on prometheus
Ref: https://pkg.go.dev/github.com/cosmos/cosmos-sdk/telemetry#Config
---
I have...
I have...

chore(price-feeder): update prometheus example config

---

x/ibctransfer/keeper/util_test.go

The transfer tests pass using the version of [ibc-go from this PR](https://github.com/umee-network/ibc-go/pull/2), which is still v3, with [this version of the branch](https://github.com/umee-network/umee/tree/8f40d114c6464a9bb5753e29d12ba3e59f486ce4) (when it was still using ibc-go v3).
Since the branch has now moved to v5, I have added the import of `github.com/cosmos/ibc-go/v5/modules/apps/transfer/types`, but if you still want to go back to the v3 fork of ibc-go, then you can just change the import to use v3.
closes: #XXXX
---
I have...
your handle next to the …

fix: transfer tests

---

README.md

Adds GB info to the release matrix.
---
I have...
I have...

docs: update release matrix

---

tests/e2e/scripts/hermes_bootstrap.sh

closes: #XXXX
---
I have...
I have...

fix: removed unknow field 'filter' from hermes config file

---

CHANGELOG.md
README.md
RELEASE_NOTES.md
go.mod
go.sum

Updates Gravity Bridge dependencie. That update disables most of the Gravity Bridge messages.
---
I have...
I have...

feat: disable gravity bridge messages

---

x/leverage/client/tests/suite.go

Removes a superfluous TODO (see comment)
closes: #1351
---
I have...
I have...

chore: remove TODO

---

CHANGELOG.md
x/leverage/keeper/borrows.go
x/leverage/keeper/collateral.go
x/leverage/keeper/collateral_test.go
x/leverage/keeper/exchange_rate.go
x/leverage/keeper/genesis.go
x/leverage/keeper/grpc_query.go
x/leverage/keeper/interest.go
x/leverage/keeper/internal_test.go
x/leverage/keeper/invariants.go
x/leverage/keeper/iter.go
x/leverage/keeper/keeper.go
x/leverage/keeper/liquidate.go
x/leverage/keeper/oracle.go
x/leverage/keeper/reserves.go
x/leverage/keeper/reserves_test.go
x/leverage/keeper/store.go
x/leverage/keeper/supply.go
x/leverage/keeper/validate.go
x/leverage/types/errors.go

Stylistic and validation changes only.
- Moved all `KVStore` get/set functions to `store.go`, except iterators in `iter.go` and registry+cache in `token.go`
- Cleaned up `KVStore` getters and setters
- All `KVStore` setters validate their inputs as a last line of defense, checking for negative amounts, empty addresses, invalid denoms, and swapped token/uToken denoms. `setInterestScalar` also rejects values less than `1.0`. The resulting error messages now contain the type of field that was invalid (e.g. "collateral").
- Lowercased some getters / setters that should not be exported
- Removed some unused getters / setters in `TestKeeper` and a duplicate getAllBadDebts in `genesis.go`
- Shortened `GetReserveAmount` and `GetCollateralAmount` by removing `Amount`
- Changed `GetReserves` and …

refactor: standardize leverage KVStore getters

---

price-feeder/CHANGELOG.md
price-feeder/oracle/filter.go
price-feeder/oracle/oracle.go
price-feeder/oracle/provider/binance.go
price-feeder/oracle/provider/bitget.go
price-feeder/oracle/provider/coinbase.go
price-feeder/oracle/provider/gate.go
price-feeder/oracle/provider/huobi.go
price-feeder/oracle/provider/kraken.go
price-feeder/oracle/provider/okx.go
price-feeder/oracle/provider/provider.go
price-feeder/oracle/provider/telemetry.go

closes: #1373 
---
I have...
I have...

feat: price-feeder telemetry standard

---

app/app.go

Fix configurator setup
BTW: in v3 (`main`) this is already correctly implemented.
---
I have...
I have...

fix: configurator setup

---

price-feeder/price-feeder.example.toml

Set gas_adjustment to 1 in order to avoid fees errors when trying to submit votes with multiple assets
---
I have...
I have...

chore: update price-feeder example config

---

app/app.go

Baseapp was missing a version
---
I have...
I have...

fix: set version for the base app

---

app/app.go
contrib/scripts/umeemainnet_fork.sh

- Adds migrations orders 
closes: #XXXX
---
I have...
I have...

feat: set migrations orders

---

ante/fee.go

Ref: https://github.com/umee-network/umee/pull/1411/files#r973809128
---
I have...
I have...

perf(ante/fee): optimize requiredFees calculation

---

app/upgrades.go
app/upgrades/v3/min_commission.go
app/upgrades/v3/min_commission_test.go
app/upgrades/v3/staking_util_test.go
contrib/scripts/umeemainnet_fork.sh

closes: #XXXX
---
I have...
I have...

chore: fix typo

---

CHANGELOG.md
RELEASE_NOTES.md
ante/fee.go
ante/fee_test.go
app/params/app_settings.go
app/test_helpers.go
cmd/umeed/cmd/app_creator.go
tests/e2e/e2e_setup_test.go
util/sim/deliver.go
x/leverage/client/tests/suite.go
x/oracle/client/tests/suite.go

+ Adding a first version of the release notes
+ backported changelog notes related to v1.1 release
---
I have...
I have...

docs: release notes draft

---

tests/e2e/scripts/price_feeder_bootstrap.sh

We increased gas to 140k, so we can keep small adjustment.
This is to merge after v3 release.
---
I have...
I have...

test: 1.2 gas_adjustment in price-feeder e2e tests

---

price-feeder/CHANGELOG.md
price-feeder/go.mod

- This enable us to release peggo v1
closes: #XXXX
---
I have...
I have...

fix: moved to v300rc1

---

util/genmap/list.go
x/oracle/keeper/reward.go
x/oracle/keeper/reward_unit_test.go

fix: oracle.RewardBallotWinner detect duplicated uumee

---

go.mod
go.sum

backporting the "disable slashing"

chore: update gravity bridge

---

CHANGELOG.md
RELEASE_NOTES.md
go.mod
go.sum

+ bump the gravity bridge
+ release notes for v3.0.2
---
I have...
I have...

fix: update & fix gravity bridge

---

price-feeder/CHANGELOG.md
price-feeder/oracle/convert.go
price-feeder/oracle/oracle.go
price-feeder/oracle/oracle_test.go
price-feeder/oracle/prices.go
price-feeder/oracle/util.go
price-feeder/oracle/util_test.go
price-feeder/router/v1/oracle.go
price-feeder/router/v1/response.go
price-feeder/router/v1/router.go
price-feeder/router/v1/router_test.go

I did some performance measurements before and after this change and the timing difference is negligible. That said, I think we could get some performance improvements by computing these per-provider prices first and passing them to the convert/filter/compute functions however it will require a decent amount of re-factoring that would make this PR much larger.
- Added additional API routes for the price-feeder to debug the per-provider computed prices
- Remove unused error handling from ComputeVWAP
- Updated the lock on the Oracle.prices variable to lock when writing
closes: https://github.com/umee-network/umee/issues/1263#event-7378865002
---
I …

feat(price-feeder): computed price api routes

---

CONTRIBUTING.md
RELEASE_NOTES.md

Let's discuss release procedure.
Do we want to:
1. keep as is: both API breaking as well as consensus breaking changes requires major version bump. 
* Pro: more major release (v3, v4, v5...), 
* Cons: we need to update proto, scripts, go.mod and all import path whenever we bump, it doesn't really follow semver.
2. adopt IBC release strategy: https://github.com/cosmos/ibc-go/blob/main/RELEASES.md as well as many core blockchains (go-ethereum, avalanche...)
* Pro / Cons: inverse of the "keep as is" 
Personally I'm leaning towards IBC strategy, because we more target API. 
This PR proposes updates to adopt option `2.`.
---
I have...
_All items are …

docs: update release procedure

---

.mergify.yml

We changed release model to keep v3 as long as it's API compatible.
---
I have...
I have...

chore: update mergify to new release scheme

---

app/upgrades.go

Adds v3.1 upgrade handler.
---
I have...
I have...

feat: add v3.1 upgrade handler

---

price-feeder/README.md

Bitget was missed as a provider in our readme in #1328
I also fixed a couple dead links that we haven't seen because of our CI cacheing 
---
I have...
I have...

docs: update price-feeder docs

---

price-feeder/CHANGELOG.md
price-feeder/price-feeder.example.toml

closes: #XXXX
---
I have...
I have...

chore: update example price feeder config

---

price-feeder/CHANGELOG.md
price-feeder/oracle/convert.go
price-feeder/oracle/convert_test.go
price-feeder/oracle/oracle.go

- Only setting this funcs to public helps a lot ^^
---
I have...
I have...

feat: change funcs to public

---

price-feeder/oracle/provider/websocket_controller.go

Log output can be very long when using with peggo and this doesn't seem super necessary. Could always be added temporarily by a dev.
---
I have...
I have...

chore: Remove websocket read log

---

README.md

docs: update compatibility matrix

---

.github/workflows/tests.yml

CI is failing due to tparse issues, eg: https://github.com/umee-network/umee/actions/runs/3361011925/jobs/5571014905
---
I have...
I have...

chore: update tparse

---

price-feeder/CHANGELOG.md
price-feeder/config/currency_provider_tracker.go
price-feeder/oracle/provider/osmosisv2.go

closes: #1531
---
I have...
I have...

feat: add osmosis-api asset pairs REST endpoint

---

go.mod
go.sum
price-feeder/go.mod
price-feeder/go.sum

closes: #XXXX
---
I have...
I have...

chore: bump cosmos-sdk to 0.46.4

---

docs/design_docs/010-market-params.md
proto/umee/leverage/v1/leverage.proto
proto/umee/oracle/v1/oracle.proto
swagger/swagger.yaml
x/leverage/types/leverage.pb.go
x/oracle/types/events.pb.go
x/oracle/types/query.pb.gw.go

Improve leverage proto docs.
---
I have...
I have...

docs(leverage): update market params docs

---

app/app.go
x/oracle/keeper/msg_server.go
x/oracle/module.go

Provide a way to enable some oracle features only in experimental mode.
To enable experimental mode you have to build using:
```
make build-experimental
```
---
I have...
I have...

feat: add experimental flag to oracle msg server

---

price-feeder/price-feeder.example.toml

This price feeder config update allows validators to vote on the price of: 
* CRO
* DAI
* ETH
* BTC
---
I have...
I have...

chore: update price-feeder config

---

docs/design_docs/011-historacle-pricing.md

closes: #XXXX
---
I have...
I have...

docs: add scenario to historacle spec

---

price-feeder/price-feeder.example.toml

PR to remove FTX from the price feeder example config.
---
I have...
I have...

fix: remove ftx from default price-feeder config

---

price-feeder/price-feeder.example.toml

Add the 3 highest volume providers for WBTC that we currently use. (https://www.coingecko.com/en/coins/wrapped-bitcoin#markets)
---
I have...
I have...

chore: Add WBTC to example price feeder config

---

x/oracle/genesis.go
x/oracle/keeper/genesis.go
x/oracle/keeper/genesis_test.go
x/oracle/keeper/historic_price.go
x/oracle/keeper/historic_price_test.go
x/oracle/simulations/genesis.go
x/oracle/types/genesis.go
x/oracle/types/genesis_test.go
x/oracle/types/keys.go
x/oracle/types/keys_test.go

- Separated the calculation and getter/setter logic for historical prices, medians, and median deviations.
- Added historical prices, medians, and median deviations state to InitGenesis and ExportGenesis
- Fixed parsing from historic prices key
closes: https://github.com/umee-network/umee/issues/1541
---
I have...
I have...

feat(oracle): Add historacle state to genesis

---

price-feeder/CHANGELOG.md

CL update for price feeder v2
---
I have...
I have...

docs(price-feeder): changelog update

---

.mergify.yml

Updates the price feeder backport rules
---
I have...
I have...

ci: update price feeder backport

---

app/upgrades.go

closes: #XXXX
---
I have...
I have...

chore: update plan name for v3.2

---

.github/workflows/release.yml
CHANGELOG.md
README.md
RELEASE_NOTES.md

Updates:
+ release notes
+ README
+ notes about Github binary release
+ notes a `libwasmvm.x86_64.so v1.1.1` dependency
---
I have...
I have...

chore: v3.2 Release Notes

---

docs/design_docs/011-historacle-pricing.md

Updates the historacle spec to allow for use by both the leverage module & ibc rate limiting
---
I have...
I have...

docs: historic spec updates

---

README.md
RELEASE_NOTES.md

This pull request contains updated release notes for running `v3.2.0` with `cosmwasm`
closes: #XXXX
---
I have...
I have...

chore: update the instuction for running v3.2.0 with cosmwasm

---

price-feeder/oracle/oracle.go

Fixes a price feeder issue where any missing exchange rate was causing validators to vote on nothing.
---
I have...
I have...

fix(price-feeder): handle missing rates properly

---

price-feeder/CHANGELOG.md

Updates the price feeder changelog for the expected v2.0.1 release
---
I have...
I have...

docs: update price-feeder changelog for v2.0.1

---

x/oracle/abci_test.go
x/oracle/keeper/historic_price.go

closes: #1619
---
I have...
I have...

test: Add Oracle enblocker test to test historacle functionality

---

go.mod
go.sum
price-feeder/go.mod
price-feeder/go.sum

IBC v5.1 was retracted and we should update to v5.2
---
I have...
I have...

chore: bump ibc-go

---

.github/workflows/price-feeder-docker.yml
.github/workflows/price-feeder-release.yml

Update release tags for price feeder docker release

chore: remove latest flavor for price-feeder docker release

---

.github/workflows/price-feeder-docker.yml
.github/workflows/price-feeder-release.yml
.github/workflows/proto.yml
price-feeder/.goreleaser.yml
price-feeder/LICENSE

Fixes: 
* price-feeder docker release
* price-feeder tarball release (missing files)
* proto CI
---
I have...
I have...

fix: price-feeder and proto CI

---

app/app.go
util/checkers/proposal.go
x/leverage/keeper/internal_test.go
x/leverage/keeper/keeper.go
x/leverage/keeper/keeper_test.go
x/leverage/keeper/msg_server.go
x/leverage/keeper/msg_server_test.go
x/leverage/keeper/suite_test.go

Gov module address is known from the begging, so we can use it in `ValidateBasic` -> `ValidateProposal`.
---
I have...
I have...

feat: simplify validate proposal

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/debug.yml
.github/workflows/dependencies-review.yml
.github/workflows/linkchecker.yml
.github/workflows/lint-pr.yml
.github/workflows/lint.yml
.github/workflows/price-feeder-docker.yml
.github/workflows/price-feeder-release.yml
.github/workflows/proto.yml
.github/workflows/release.yml
.github/workflows/simulations.yml
.github/workflows/tests.yml
.github/workflows/umee-docker.yml
app/app.go

Optimizes CI by killing ongoing workflows on update.
---
I have...
I have...

feat: auto kill CI workflows on update

---

RELEASE_NOTES.md

Adding link to docker images
---
I have...
I have...

docs: Update RELEASE_NOTES.md

---

app/upgrades.go
x/oracle/keeper/migrations.go

Changes the v3.4 version name to v4.0
---
I have...
I have...

chore: change v3.4 to v4.0

---

tests/e2e/e2e_test.go
tests/grpc/historical.go
tests/grpc/price_listener.go
tests/grpc/price_store.go
tests/grpc/umee_client.go
x/oracle/keeper/grpc_query.go

- Fix MedianDeviations grpc query; appending to the array of prices instead of adding
- Add e2e grpc test for median deviations
---
I have...
I have...

ci(tests): median deviation e2e test

---

contrib/images/price-feeder.dockerfile
contrib/images/umee.e2e-static.dockerfile
contrib/images/umee.e2e.dockerfile
contrib/images/umeed.dockerfile
x/leverage/types/msgs.go

closes: #1697
---
I have...
I have...

perf: optimize docker builds

---

x/leverage/README.md

closes: #XXXX
---
I have...
I have...

docs: add historacle+leverage info to spec

---

docs/design_docs/005-liquidation.md

closes: #XXXX
---
I have...
I have...

docs: Update 005-liquidation.md

---

app/upgrades.go

Registers an upgrade from v4.0-rc1 to v4.0-rc3. This is a non-operating upgrade.
Necessary for a fix on canon-2 after the [rc3 pruning fix](https://github.com/umee-network/umee/pull/1720/files) is merged
---
I have...
I have...

feat: register upgrade for v4.0-rc3

---

app/upgrades.go

Registers the rc4 upgrade handler for the canon-2 testnet upgrade.
---
I have...
I have...

feat: register rc4 upgrade

---

x/leverage/README.md

closes: #XXXX
---
I have...
I have...

docs: update leverage readme for historic per-token calcs

---

CHANGELOG.md
README.md
RELEASE_NOTES.md

v4.0 release notes :^) 
Will not merge until we have stakeholders agreed on Umee v4.0 & PF v2.0.3
---
I have...
I have...

docs: v4.0 release notes

---

x/uibc/keys.go
x/uibc/quota/keeper/quota.go

1. uses new prefix store abstraction to deal with keys
2. fixes denom extranction
---
I have...
I have...

fix: ibc quota iterator

---

app/upgrades.go

Let's cleanup "test" upgrade handlers. Especially that we are going to remove canon-2

chore: remove rc upgrade handlers

---

RELEASE_NOTES.md
go.mod
go.sum
price-feeder/go.mod
price-feeder/go.sum

chore: Updating Cosmos SDK to 0.46.9 and Tendermint to 0.34.26

---

price-feeder/CHANGELOG.md

chore: update price feeder changelog

---

app/upgrades.go

Registers the upgrade handler for the coming v4.0.1 release
---
I have...
I have...

feat: register v4.0.1 upgrade

---

CHANGELOG.md
RELEASE_NOTES.md

closes: #XXXX
---
I have...
I have...

docs: update release notes & changelog

---

.mergify.yml
app/upgrades.go

- renames the v4.1 release (uibc / ibc quota) to v4.2
- updates mergify to target new `release/v4.1.x` branch

chore: update upgrades and mergify to v4.1

---

price-feeder/price-feeder.example.toml

closes: #XXXX
---
I have...
I have...

chore: update PF example config

---

app/upgrades.go

Speeding this one directly onto the 4.1 branch if reviews too slow

fix: plan name for rc2 binary

---

.mergify.yml

chore(ci): update mergify config for the merge-queue

---

.github/workflows/lint-pr.yml

adding exception for merge-queue

chore(ci): pr-title linter exception

---

price-feeder/price-feeder.example.toml

Updates price feeder config to point to the autohealing osmosis api
---
I have...
I have...

chore(pf): update suggested config

---

Makefile

closes: #XXXX
---
I have...
I have...

Fix whitespace for Make 4.3

---

x/oracle/keeper/historic_avg.go
x/oracle/keeper/historic_avg_test.go

tests: avg keeper shift and cycle tests

---

x/oracle/keeper/historic_avg.go
x/oracle/keeper/historic_avg_test.go

https://linear.app/umee/issue/UMEE-308/update-avgkeeperupdateavgcounter-to-handle-chain-halt

tests: avg keeper halt check

---

app/params/app_settings.go
price-feeder/router/v1/router.go
tests/e2e/e2e_setup_test.go
util/decmath/decmath.go
util/genmap/genmap_test.go
x/leverage/keeper/liquidate_test.go
x/leverage/types/proposal.go
x/oracle/abci_test.go
x/oracle/keeper/historic_avg_test.go
x/oracle/keeper/msg_server.go
x/oracle/types/ballot_test.go
x/uibc/quota/keeper/grpc_query_test.go
x/uibc/quota/keeper/msg_server_test.go
x/uibc/quota/keeper/quota.go

chore: auto lint

---

x/uibc/quota/keeper/quota.go

closes: #XXXX
---
I have...
I have...

fix: fix the get avg price for denoms

---

tests/e2e/e2e_ibc_test.go
tests/grpc/client/tx/gov.go
x/oracle/keeper/historic_avg.go
x/oracle/keeper/historic_avg_test.go
x/uibc/quota/keeper/grpc_query_test.go

* adding few more edge cases
* linter

chore: more avg tests

---

app/upgrades.go

change upgrade name from beta to normal

chore: v4.2 upgrade handler name

---

x/incentive/params.go
x/leverage/types/params.go
x/oracle/keeper/migrations.go
x/oracle/types/params.go
x/uibc/params.go

Reduce boilerplate of consts and defaults which are used only once , or private.

DNM: chore: reduce not used exported consts

---

Makefile
README.md

Adds instructions about recommended database.

docs: update information about db backend

---

RELEASE_NOTES.md

docs: update release notes with peggo gas-prices

---

price-feeder/README.md

docs: adding more instructions about price feeder config

---

go.mod
go.sum

feat: GB phase out phase2: disable cosmos -> ethereum transfers

---

app/app.go
app/experimental_appconfig.go
app/stable_appconfig.go

chore: update cosmwasm wiring

---

.github/workflows/release-umee.yml

beta releases are skipped from auto release.

fix: add beta to releaser workflow

---

x/uibc/module/abci.go

fix: avoid panics in uibc endblocker

---

CHANGELOG.md
RELEASE_NOTES.md
app/upgrades.go

* updated the upgrade plan name (removed beta tag)

chore: v4.3 release notes

---

Makefile

Ths pull request container fixes for build version to binary
closes: #XXXX
---
I have...
I have...

fix: fix the build version

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/lint.yml

There are still few left overs of the price feeder config

chore: cleanup price-feeder from workflows

---

.github/workflows/tests.yml
.goreleaser.yml
RELEASE_NOTES.md

chore: use tar.gz for Github releases

---

Makefile

there was a "w" accidentally inserted in Makefile

fix: Makefile

---

tests/simulation/state.go

closes: #XXXX
---
I have...
I have...

fix: do not use random eth addresses for sims

---

go.mod
go.sum

closes: #XXXX
---
I have...
I have...

build: bump proto version

---

app/upgrades.go

chore: set upgrade name to alpha

---

CHANGELOG.md
x/incentive/keeper/scenario_test.go
x/incentive/keeper/update.go

closes: #XXXX
---
I have...
I have...

fix: incentive program rewards when zero bonded

---

RELEASE_NOTES.md
app/upgrades.go

chore: v4.4 release notes

---

util/coin/dec.go
util/coin/fixtures.go
x/leverage/types/token.go
x/uibc/quota/keeper/msg_server.go

Added & updated few coin common helper method to be used in tests (I'm using them already in an active branch).

feat: coin helpers update

---

.github/workflows/simulations.yml
.github/workflows/tests.yml
app/export.go

skip the e2e tests and skip the simulation tests when the `skip-e2e-test`  label  present on pull request
---
I have...
I have...

chore: skip e2e test on github actions with label

---

x/incentive/client/cli/query.go
x/oracle/client/cli/query.go

small cleanups in the client code

chore: use cli.PrintOrErr

---

Makefile
contrib/images/umeed.dockerfile

Adding user to the container (stride uses it in few tests)
---
I have...
I have...

chore: update docker files

---

CHANGELOG.md
README.md
RELEASE_NOTES.md

backporting v4.1.1 release notes and changelog

v4.1.1 release notes

---

CHANGELOG.md
go.mod
go.sum

closes: #XXXX
---
I have...
I have...

chore: barberry patch

---

app/wasm/query/handle_leverage.go

closes: #XXXX
---
I have...
I have...

chore: fix cw query for leverage max borrow

---

util/coin/fixtures.go
x/incentive/README.md
x/incentive/keeper/scenario_test.go
x/incentive/keeper/unit_test.go
x/incentive/keeper/update.go

squash PR 2124 due to unsigned commits

test: more incentive test flows

---

proto/umee/metoken/v1/query.proto
x/metoken/metoken.pb.go

closes: #XXXX
---
I have...
I have...

chore: proto lint for metoken query proto

---

swagger/proto-config-gen.json
swagger/swagger.yaml

closes: #XXXX
---
I have...
I have...

chore: update the proto swagger docs for ugov and metoken

---

x/leverage/types/codec.go

closes: #XXXX
---
I have...
I have...

fix: fixing the amino-json sign on MsgLeveragedLiquidate

---

app/app.go
app/test_helpers.go
app/wasm/test/cosmwasm_test.go
app/wasm/test/umee_cw_test.go
x/metoken/client/tests/cli_test.go
x/metoken/client/tests/suite.go
x/metoken/client/tests/tests.go
x/metoken/keeper/intest/grpc_query_test.go
x/metoken/keeper/intest/interest_test.go
x/metoken/keeper/intest/keeper_test.go
x/metoken/keeper/intest/msg_server_test.go
x/metoken/keeper/intest/reserves_test.go

closes: #XXXX
---
I have...
I have...

chore:  making unit tests to experimental for metoken

---

x/ugov/client/cli/query.go

closes: #XXXX
---
I have...
I have...

chore: add emergency group ugov cli query

---

app/upgrades.go

closes: #XXXX
---
I have...
I have...

fix: fix the store upgrade for metoken on v6.1.0

---

go.mod
go.sum

chore: Bump Cosmos SDK to v0.46.15

---

CHANGELOG.md
README.md
RELEASE_NOTES.md
app/upgrades.go
x/oracle/migrations/exg_rates_migrations.go

+ changelog update
+ migrator function update

chore: prepare v6.1 release

---

go.mod

chore: remove go.mod cosmos-proto compatibility comment

---

README.md
RELEASE_NOTES.md

closes: #XXXX
---
I have...
I have...

docs: update release notes

---

app/upgrades.go

closes: #XXXX
---
I have...
I have...

chore: fix the upgrade handler for canon-4
