umee-network/umee

app/app.go, x/ibctransfer/keeper/chain_test.go, x/ibctransfer/keeper/keeper.go, x/ibctransfer/keeper/keeper_test.go, x/ibctransfer/keeper/util_test.go, x/ibctransfer/module.go, x/ibctransfer/types/expected_keepers.go
Create a forked `x/ibctransfer` based on the ICS-20 module that wraps a few methods so we can automatically add metadata on the fly as assets are transferred to/from Umee.
closes: #49
----
I have...
I have...
=> feat: x/ibctransfer

Dockerfile, go.mod, go.sum
Bump gravity bridge to v0.2.4. Replaces https://github.com/umee-network/umee/pull/82
----
I have...
I have...
=> chore: bump gravity bridge version

x/peggy/keeper/pool.go, x/peggy/keeper/pool_test.go
This solution uses the same ReverseIterator as `IterateOutgoingPoolByFee` (https://github.com/umee-network/umee/blob/main/x/peggy/keeper/pool.go#L285) which is the function used to get the TXs that'll make it to the created batch. It's very important to use the same ordering criteria for when we estimate fees and for when we actually create a batch.
Also a simple test was added to check that a new tx with a higher fee makes it to the batch fee estimation and that a new tx with a low fee doesn't make it.
closes: #222
----
I have...
your handle next to the items …
=> fix: x/peggy: Use reverse iterator and add tests

x/peggy/keeper/msg_server.go, x/peggy/keeper/msg_server_test.go
Require batch creators to be validator orchestrators.
closes: #230
----
I have...
I have...
=> fix: require x/peggy batch creators to be validator orchestrators

app/app.go
This was a bug that prevented valsetUpdates creation when a validator unbonds. 
It was failing because:
The hook that updates the lastUnbondingHeight runs after both BeginBlocker and EndBlocker. Meaning in Endblocker this condition is never met: (lastUnbondingHeight == ctx.BlockHeight())  to create a new valsetUpdate
----
I have...
I have...
=> fix: Place x/peggy EndBlocker after x/staking

x/peggy/client/cli/tx.go, x/peggy/keeper/attestation.go, x/peggy/keeper/keeper.go
- Made AttestationHandler of x/peggy/Keeper private
- Allow optional 0x prefix on set-orchestrator-address for private key and signature.
----
I have...
I have...
=> refactor: x/peggy: Allow prefixed and non prefixed hex + Make keeper field private

x/leverage/keeper/token.go
Use `keeper.cdc` for all types other than `sdk.Int` and `sdk.Dec` in `x/leverage` - as it turns out, only `Token` needed any updates.
----
I have...
I have...
=> refactor: codec Marshal and Unmarshal for Token

price-feeder/oracle/oracle.go
Shortens the time between votes for the price feeder. It was too long, causing the exchange rates to periodically not get voted on.
Ref, conversation in #305
----
I have...
I have...
=> fix: price feeder timing

x/leverage/keeper/borrows.go, x/leverage/keeper/grpc_query.go, x/leverage/keeper/keeper.go, x/leverage/keeper/keeper_test.go
Adds borrow limit restrictions to `MsgWithdrawAsset`, `MsgBorrowAsset`, and `MsgSetCollateral` (when disabling).
Fix unrelated tests that were borrowing more than `CollateralWeight` = 0.1 for `uumee` would allow.
closes: #213 
----
I have...
I have...
=> feat: borrow limit restrictions

x/oracle/client/cli/tx.go, x/oracle/client/tests/cli_test.go, x/oracle/client/tests/suite.go
- Add support for tx commands to the x/oracle module (there's only 1)
----
I have...
I have...
=> feat: x/oracle TX CLI commands

app/beta/test_helpers.go, x/leverage/client/tests/suite.go
Clean up import order in some of the test helpers. I forgot to push this fix at the end of my previous PR.
----
I have...
I have...
=> chore: import order

x/leverage/keeper/oracle.go, x/leverage/types/errors.go
`TokenPrice`, which is the leverage module's single path to `x/oracle`, is not protected against nil/negative/zero exchange rates, and oracle panics. 
It will return errors in those cases.
closes: #329
----
I have...
I have...
=> fix: ensure safety against empty exchange rates

x/oracle/client/tests/suite.go
Add an additional CLI test for the oracle module. This pretty much wraps it up apart from querying pre-votes and votes, which require a price-feeder running.
closes: #266
----
I have...
I have...
=> chore: add additional oracle CLI tests

x/oracle/abci.go, x/oracle/keeper/ballot.go, x/oracle/keeper/msg_server.go, x/oracle/types/errors.go, x/oracle/types/msgs_test.go, x/oracle/types/vote.go, x/oracle/types/vote_test.go
Removes oracle abstaining logic, adds erroring for votes on non-positive exchange rates
closes: #360
----
I have...
I have...
=> refactor: remove oracle vote abstaining

price-feeder/oracle/client/client.go, price-feeder/price-feeder.example.toml
Handles the edgecase where the tx response code for a prevote is not zero, but doesn't error. Happens when a signature fails, e.g. the wrong chain is in the config.
Also updated the example config with the beta chain name to make it a bit more plug-and-play.
----
I have...
I have...
=> chore: price-feeder: handle wrong tx response code

tests/e2e/docker/hermes.Dockerfile
⬆️ Upgrade Hermes `0.9.0` -> `0.10.0` in end to end test
This is a simple change which updates the source dockerfile for the hermes build in the end-to-end test. It updates the version.
I have...
I have...
=> chore: bump hermes to 0.10.0 for e2e tests

cmd/umeed/cmd/root.go
As far as I can tell, both collect-gentxs commands are identical.
closes: #394
----
I have...
I have...
=> fix: Remove gravity bridge collect-gentxs

x/leverage/keeper/interest.go, x/leverage/keeper/oracle.go, x/leverage/spec/06_events.md, x/leverage/types/events.go
Add events and logging when interest accrues, reserves are added, or oracle rewards are funded.
Interest epoch event also records block height and unix time.
----
I have...
I have...
=> feat: interest epoch and fund oracle events

x/leverage/keeper/borrows.go, x/leverage/keeper/exchange_rate.go, x/leverage/keeper/invariants.go, x/leverage/keeper/keeper.go, x/leverage/keeper/keeper_test.go, x/leverage/module.go, x/leverage/types/keys.go, x/leverage/types/keys_test.go
- Implemented invariant functions of `x/leverage` module
- `ExchangeRatesInvariant` checks if the amount is lower than one
- `ReserveAmountInvariant` checks if the amount is negative
- `CollateralAmountInvariant` checks if the amount is negative or zero
- `BorrowAmountInvariant` checks if the amount is negative or zero
- `BorrowAPYInvariant` checks if the amount is negative
- `LendAPYInvariant` checks if the amount is negative
ref: #354  
----
I have...
I have...
=> feat: leverage invariants

x/oracle/types/ballot.go, x/oracle/types/ballot_test.go
Keeps the standard deviation calculation from rounding 
----
I have...
I have...
=> fix: use ApproxSqrt instead of math.Sqrt for calculating standard deviation

x/leverage/keeper/keeper.go, x/leverage/types/expected_types.go
`bankkeeper.SpendableCoins` gets an account's balances, minus locked coins.
Context from the [sdk](https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/keeper/view.go#L169)
> LockedCoins returns all the coins that are not spendable (i.e. locked) for an account by address. For standard accounts, the result will always be no coins. For vesting accounts, LockedCoins is delegated to the concrete vesting account type.
While it has not been explicitly discussed whether we are using vesting accounts, this PR ensures that they would be bug-free when interacting with `x/leverage` by replacing calls to `bankkeeper.GetBalance(denom)` for non-module accounts with `bankkeeper.SpendableCoins.AmountOf(denom)` or similar code.
It also cleans up some unused functions in `expected_types.go`
----
*All …
=> refactor: SpendableCoins replaces GetBalance for non-module accounts

price-feeder/oracle/oracle.go
Fixes an issue where if we can't get the block height (e.g., if the `tmrpc_endpoint` in the config is unreachable), we'd be stuck in a loop without any error messages. 
----
I have...
I have...
=> fix: price-feeder : return an error if we can't get the block height

app/app.go, app/beta/app.go, app/modules.go
Override `ValidateGenesis` for the `x/genutil` module so we can have `validate-genesis` pass for gentxs that contain delegate key messages.
closes: #409
----
I have...
I have...
=> fix: validate genesis command

x/oracle/types/vote.go, x/oracle/types/vote_test.go
Parses tuples more strictly. Resolves one of the concerns found in ToB audit. 
progress on: #416
----
I have...
I have...
=> fix: x/oracle: parse tuples more strictly

x/oracle/keeper/keeper.go, x/oracle/keeper/keeper_test.go
Removes the hard-coded usd rate & its test, so we can support stablecoins : 
```go
if strings.Contains(strings.ToUpper(denom), types.USDDenom) { 
return sdk.OneDec(), nil 
} 
```
closes: #435
----
I have...
I have...
=> fix: remove hard-coded usd rate

infra/packer/Dockerfile.build
Pin peggo to version 0.2.1 in image build
=> chore: pin peggo v0.2.1 in image build

infra/packer/umee-node-dist.pkr.hcl
Double the cpu cores available to packer for building to reduce failure rate (was 1 core, now is 2); this will also provide more memory and network to the gcp instance during image building.
1. The docker image build (running on github actions runners) does not ever fail -- well, the github runner has 2 cpus.
2. The packer (gcp) image builder defaults to using a 1 core machine to do the work, and I believe this is why it is so flaky right now, it is resource starved.
=> chore: double cpu cores in packer build to reduce failure

infra/packer/umee-node-dist.pkr.hcl
There is a race condition between cloud-init and the packer code which is causing the intermittent apt failures (hypothesis).
https://askubuntu.com/questions/663296/intermittent-apt-get-install-issues-when-creating-an-ami-using-packer
https://github.com/hashicorp/packer/issues/2639
suggested fix:
```
provisioners:
- type: shell
inline:
- /usr/bin/cloud-init status --wait
```
=> fix: wait for cloud init during packer gcp build to avoid apt race condition

x/leverage/keeper/keeper.go, x/leverage/keeper/keeper_test.go
See issue for problem symptoms and discussion of solution
closes: #490
----
I have...
I have...
=> fix: WithdrawAsset - move error check to before coins.Sub to prevent panic

price-feeder/oracle/oracle.go, price-feeder/oracle/util.go, price-feeder/oracle/util_test.go
Detects faulty providers by computing the standard deviation of prices of an asset, and filtering out any prices reported which are more than `2𝜎` away from the mean. Ignores this logic for assets that do not have at least three providers, which will be an enforced minimum for non-mocked assets in a coming PR.
progress on : #451
----
I have...
I have...
=> feat: faulty provider detection

price-feeder/CHANGELOG.md, price-feeder/config/config.go, price-feeder/config/config_test.go
Force a minimum of three providers during the price-feeder's config validation. This errors on all assets, unless a "mock" provider is included.
closes: #451
----
I have...
I have...
=> feat: price-feeder: force a minimum of three providers

price-feeder/CHANGELOG.md, price-feeder/config/config.go, price-feeder/config/config_test.go
Fixes our config validation so that telemetry is no longer required 
closes: #544
----
I have...
I have...
=> fix: stop requiring telemetry during config validation

CHANGELOG.md, cmd/umeed/cmd/debug.go, cmd/umeed/cmd/root.go
Refactor the `umeed debug addr` command that comes from the SDK.
----
I have...
I have...
=> refactor: debug addr cmd

price-feeder/CHANGELOG.md, price-feeder/oracle/oracle.go, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/binance_test.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/okx_test.go, price-feeder/oracle/provider/provider.go
- Modified Binance provider to use [WebSocket](https://binance-docs.github.io/apidocs/spot/en/#aggregate-trade-streams) connection instead of `http.client`
- Modified unit tests for checking the map
- Add reconnect logic to Okx provider
ref: #509
----
I have...
I have...
=> feat: update Binance provider to use WebSocket

price-feeder/CHANGELOG.md, price-feeder/router/middleware/middleware.go, price-feeder/router/v1/router.go
Updates our cors settings to only allow GET and OPTIONS requests, and updates the options preflight handler to echo back the `Origin` header in `Access-Control-Allow-Origin` if it's in the config.
closes: #515
----
I have...
I have...
=> fix: strengthen price-feeder cors settings

price-feeder/CHANGELOG.md, price-feeder/router/v1/router.go
Only register metrics endpoint if telemetry is enabled 
closes: #572
----
I have...
I have...
=> fix: only register metrics endpoint with tel enabled

price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/kraken_test.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/provider.go
Adds subscriptions to the candlestick websockets for our providers. Necessary for implementing tvwap.
Doing calculations in a separate PR to keep this tidy. 
progress on: #542
----
I have...
I have...
=> feat: price-feeder: candlestick websocket subscriptions

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/binance_test.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/huobi_test.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/okx_test.go
- Add SubscribeTickers function to the following providers: (Okx, Huobi, Kraken, Binance)
```go
// SubscribeTickers subscribe all currency pairs into ticker and candle channels.
func (p *provider) SubscribeTickers(cps ...types.CurrencyPair) error {
....
}
```
ref: [#181](https://github.com/umee-network/peggo/issues/181)
----
I have...
I have...
=> feat: add SubscribeTickers func to providers

price-feeder/CHANGELOG.md, price-feeder/oracle/oracle.go, price-feeder/oracle/oracle_test.go, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/huobi_test.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/mock.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/osmosis.go, price-feeder/oracle/provider/provider.go, price-feeder/oracle/util.go
Uses tvwap for our providers when available.
Only thing left here is refactoring our anomaly detection logic for these candles - putting that in this PR would've been too much to review.
progress on: #542
----
I have...
I have...
=> feat: tvwap calculations

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/provider.go
Kraken's candle timestamps come in as seconds, not milliseconds, so we need to convert it like we do with huobi. 
Fixes an issue where kraken's candle history was being shortened to the most recent one, making tvwap inaccurate. 
----
I have...
I have...
=> fix: price-feeder: correct kraken timestamp unit

x/leverage/types/codec.go
Add missing message types to codec registration.
----
I have...
I have...
=> chore: update x/leverage messages codec 

networks/umee-1/README.md, price-feeder/CHANGELOG.md, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/provider.go
- Split subscription of ticker and candle channels for the following providers: Okx, Binance, Huobi, and Kraken
- Add error check for `websocket.CloseAbnormalClosure` to Kraken when EOF occurs to avoid having the following 
----
I have...
I have...
=> refactor: split subscribe ticker and candle channels

price-feeder/oracle/oracle.go, price-feeder/oracle/util.go, price-feeder/oracle/util_test.go
closes: #XXXX
----
I have...
I have...
=> chore: price-feeder housekeeping

infra/packer/Dockerfile.build, infra/packer/bin/build-dist, infra/packer/umee-node-dist.pkr.hcl
* Remove Beta Build from Image
* Use binary release build for peggo instead of building ourselves
* Use binary release build for price-feeder instead of building ourselves
* Upgrade Golang from `1.17.5` -> `1.17.8`
=> chore: Remove beta + performance improvements to build (packer imaging)

proto/umee/leverage/v1beta1/query.proto, x/leverage/client/cli/query.go, x/leverage/client/tests/suite.go, x/leverage/keeper/grpc_query.go, x/leverage/spec/03_queries.md, x/leverage/types/query.pb.go, x/leverage/types/query.pb.gw.go
Plus some typo fixes in query proto file
----
I have...
I have...
=> feat: CollateralValue and LiquidationLimit queries

price-feeder/oracle/oracle.go, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/coinbase.go, price-feeder/oracle/provider/gate.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/okx.go
Adds some measurements for Websocket reconnection attempts & candle / ticker messages being received
closes: #637
----
I have...
I have...
=> feat: price-feeder: telemetry additions

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/binance_test.go, price-feeder/oracle/provider/coinbase.go, price-feeder/oracle/provider/coinbase_test.go, price-feeder/oracle/provider/gate.go, price-feeder/oracle/provider/gate_test.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/huobi_test.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/kraken_test.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/okx_test.go
- Add verification and tests for `SubscribedPairs` with empty parameters
closes: #672 
----
I have...
I have...
=> fix: Oracle price feeders add verification of empty subscribed pairs

price-feeder/CHANGELOG.md, price-feeder/cmd/price-feeder.go, price-feeder/config/config.go, price-feeder/oracle/oracle.go, price-feeder/oracle/oracle_test.go, tests/e2e/scripts/price_feeder_bootstrap.sh
Necessary feature for non-websocket providers that take long enough to retrieve prices that it disrupts the voting mechanism, causing periodic loss of exchange rates & missed vote periods for validators.
closes: #674
----
I have...
I have...
=> feat: provider timeouts

x/leverage/keeper/interest.go
Should help slightly when encountering #543
=> chore: clarify negative interest time error message

infra/packer/Dockerfile.build, infra/packer/umee-node-dist.pkr.hcl
* Golang (used to build umee) `0.17.8 -> 0.18`
* Price Feeder `0.1.2 -> 0.1.4`
* Peggo `0.2.6 -> 0.2.7`
=> chore: Upgrade dependencies in built packer images

infra/packer/umee-node-dist.pkr.hcl
* price feeder `v0.1.4` -> `v0.2.0`
=> chore: bump price-feeder in packer image to v0.2.0

CHANGELOG.md, Makefile
- Add go tip to the makefile to generate easily readable coverage
- run `make test-unit-cover`
- open it in the browser with `go tool cover -html=coverage.txt`
----
I have...
I have...
=> chore: add go tool tip to makefile

CHANGELOG.md, x/leverage/simulation/operations.go, x/leverage/types/tx.go
liquidate command was using borrower address as liquidator
----
I have...
=> fix: liquidate command from-address

CHANGELOG.md, x/oracle/client/cli/query.go
Adds a miss counter query to the oracle's cli
----
I have...
I have...
=> feat: x/oracle miss counter cli command

CHANGELOG.md, x/oracle/keeper/ballot_test.go, x/oracle/keeper/grpc_query_test.go, x/oracle/keeper/keeper.go, x/oracle/keeper/keeper_test.go
Resolves a small efficiency issue with the GetExchangeRateBase function + will add some tests for it  
closes: #865
----
I have...
I have...
=> refactor: x/oracle: make GetExchangeRateBase more efficient

CHANGELOG.md, proto/umee/leverage/v1/genesis.proto, proto/umee/leverage/v1/gov.proto, proto/umee/leverage/v1/leverage.proto, proto/umee/leverage/v1/query.proto, proto/umee/leverage/v1/tx.proto, proto/umee/oracle/v1/genesis.proto, proto/umee/oracle/v1/oracle.proto, proto/umee/oracle/v1/query.proto, proto/umee/oracle/v1/tx.proto
In Cosmos SDK we are using v1beta1 because we didn't release Cosmos SDK v1 and we were not sure about the final layout.
Unfortunately this pattern got copied in other projects without asking "why". We are not creating an SDK, but a final product, so we have our upcoming next production release. 
Follow up tasks:
----
I have...
I have...
=> chore: Move proto v1beta1 to v1

CHANGELOG.md, x/leverage/client/cli/query.go
Register the missing CLI query for MarketSummary.
----
I have...
I have...
=> feat: add missing market summary CLI query

go.mod, go.sum, price-feeder/go.mod, price-feeder/go.sum
@facundomedica was able to contribute the halting fix upstream albeit still in an unversioned release.
bumps gravity module to 8d660b559b0718c6ff4e20f3b355d94501d8dbb3
ran:
```
go get github.com/Gravity-Bridge/Gravity-Bridge/module@8d660b559b0718c6ff4e20f3b355d94501d8dbb3
```
I have...
=> chore: update upstream gravity module to fix halt bug

CHANGELOG.md, Makefile
The way breaking changes for the protobuf works:
1. We had to check in a directory structure for the new build system and have breaking changes check against itself first.
2. The second step was to merge the changes to main. 
3. The third step (this PR) is to change the branch breaking changes checks against back to main.
----
I have...
=> ci: Changing branch for  breaking changes checker

.golangci.yml
- Remove lint runner warnings from `make lint`
> Note: there are still linters context warnings [because of go1.18](https://github.com/golangci/golangci-lint/issues/2649)
----
I have...
I have...
=> fix: lint runner warnings

CHANGELOG.md, x/leverage/keeper/interest.go
Makes it easier to determine which times are responsible for #543 and similar 
----
I have...
I have...
=> chore: clarify negative time elapsed error

price-feeder/CHANGELOG.md, price-feeder/oracle/util.go
Update tvwapCandlePeriod from 3 minutes to 5 minutes per our audit.
closes: #1030
----
I have...
I have...
=> fix: update tvwapCandlePeriod from 3 minutes -> 5 minutes

price-feeder/CHANGELOG.md, price-feeder/cmd/price-feeder.go, price-feeder/config/config.go, price-feeder/config/config_test.go, price-feeder/oracle/oracle.go, price-feeder/oracle/oracle_test.go, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/binance_test.go, price-feeder/oracle/provider/coinbase.go, price-feeder/oracle/provider/coinbase_test.go, price-feeder/oracle/provider/gate.go, price-feeder/oracle/provider/gate_test.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/huobi_test.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/kraken_test.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/okx_test.go, price-feeder/oracle/provider/osmosis.go, price-feeder/oracle/provider/osmosis_test.go, price-feeder/price-feeder.example.toml
Adds a feature which would allow validators to customize which websocket / rest URIs that they'd like to use. Very useful in case one of these is removed or renamed 😄 
closes: #1031
----
I have...
I have...
=> feat!: make the price feeder's uris configurable

CHANGELOG.md, price-feeder/oracle/oracle.go, proto/umee/leverage/v1/query.proto, proto/umee/oracle/v1/query.proto, x/leverage/client/cli/query.go, x/leverage/keeper/grpc_query.go, x/leverage/keeper/grpc_query_test.go, x/leverage/types/query.pb.go, x/leverage/types/query.pb.gw.go, x/oracle/client/cli/query.go, x/oracle/keeper/grpc_query.go, x/oracle/keeper/grpc_query_test.go, x/oracle/types/query.pb.go, x/oracle/types/query.pb.gw.go
Changes `Query...Request` to `Query...` for all queries in the leverage module.
Note @adamewozniak: Oracle proto has been modified as well.
closes: #1104
---
I have...
=> chore!: remove request suffix from leverage and oracle queries

CHANGELOG.md, docs/architecture/ADR-002-deposit-assets.md, docs/architecture/ADR-003-borrow-assets.md, docs/architecture/ADR-004-interest-and-reserves.md, proto/umee/leverage/v1/tx.proto, x/leverage/client/cli/tx.go, x/leverage/client/tests/tests.go, x/leverage/keeper/borrows_test.go, x/leverage/keeper/collateral_test.go, x/leverage/keeper/keeper.go, x/leverage/keeper/keeper_test.go, x/leverage/keeper/msg_server.go, x/leverage/keeper/validate.go, x/leverage/simulation/operations.go, x/leverage/simulation/operations_test.go, x/leverage/spec/01_concepts.md, x/leverage/spec/04_messages.md, x/leverage/spec/06_events.md, x/leverage/spec/README.md, x/leverage/types/codec.go, x/leverage/types/events.go, x/leverage/types/tx.go, x/leverage/types/tx.pb.go
closes: #1101
| Old Name | New Name |
| - | - |
| MsgWithdrawAsset | MsgWithdraw |
| MsgBorrowAsset | MsgBorrow |
| MsgRepayAsset | MsgRepay |
| MsgAddCollateral | MsgCollateralize |
| MsgRemoveCollateral | MsgDecollateralize |
The associated grpc services are also renamed (e.g. `WithdrawAsset` -> `Withdraw`)
Note that `MsgSupply` and `MsgLiquidate` are unchanged in this PR.
---
I have...
=> chore!: rename leverage message types

CHANGELOG.md, util/cli/print.go, x/leverage/client/cli/query.go, x/oracle/client/cli/query.go
In cli code we have a lot of code repetition related to handling error and printing proto message.
This PR introduces a `PrintOrErr` util function to reduce repeated code.
---
I have...
I have...
=> refactor: add PrintOrErr util function and improve devux in cli commands

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/osmosis.go, price-feeder/oracle/provider/osmosis_test.go
Update a deprecated osmosis endpoint that was causing the price feeder to be inaccurate
---
I have...
I have...
=> fix: update deprecated osmosis api endpoint

.github/workflows/build.yml
Each PR has duplicated build job. This changeset fixes that.
---
I have...
I have...
=> chore(github ci): remove duplicated build

CHANGELOG.md, util/checkers/doc.go, util/checkers/sign.go, x/leverage/types/tx.go, x/oracle/types/msgs.go
Util package to remove repetitions in `sdk.Msg` interface implementation (ValidateBasic and GetSigners).
This package can be extended in the future to provide more common check / validation functions.
Ref: https://github.com/umee-network/umee/issues/1194
---
I have...
I have...
=> feat: adding checkers util package

x/leverage/keeper/interest.go, x/leverage/module.go
closes: #1197
---
I have...
I have...
=> docs: cleanup todo comments

Makefile, price-feeder/Makefile
#1221 introduced a `find -name` into the `make lint`, which does not work on OSX.
```
--> Running linter
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
make: *** [lint] Error 1
```
This removes the usage of find.
---
I have...
I have...
=> fix: make lint OSX compatibility

price-feeder/CHANGELOG.md, price-feeder/oracle/convert.go, price-feeder/oracle/convert_test.go, price-feeder/oracle/filter.go, price-feeder/oracle/filter_test.go, price-feeder/oracle/oracle.go, price-feeder/oracle/oracle_test.go, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/coinbase.go, price-feeder/oracle/provider/gate.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/kraken_test.go, price-feeder/oracle/provider/mock.go, price-feeder/oracle/provider/okx.go, price-feeder/oracle/provider/osmosis.go, price-feeder/oracle/provider/provider.go, price-feeder/oracle/types/candle_price.go, price-feeder/oracle/types/candle_price_test.go, price-feeder/oracle/types/ticker_price.go, price-feeder/oracle/types/ticker_price_test.go, price-feeder/oracle/util_test.go
The TickerPrice and CandlePrice types are used across the oracle package so they are being moved to the types package to cleanup the provider code 
- Move TickerPrice and CandlePrice to the types package
- Move the NewTickerPrice and NewCandlePrice functions to the type package
- Add tests for NewTickerPrice and NewCandlePrice
closes: https://github.com/umee-network/umee/issues/936
---
I have...
I have...
=> refactor(price-feeder): Move TickerPrice and CandlePrice to types package

.github/workflows/linkchecker.yml
Fix the following error that occurs during github workflow checks:
"Error: Unable to resolve action `gaurav-nelson/github-action-markdown-link-check@1`, unable to find version `1`"
---
I have...
I have...
=> fix: Update package reference for MD link checker

.github/workflows/release.yml
Release should be triggered based on tag, not a pull request.
---
I have...
I have...
=> chore(ci): remove PR event from release workflow

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/gate.go, price-feeder/oracle/provider/huobi.go, price-feeder/oracle/provider/kraken.go, price-feeder/oracle/provider/osmosis.go, price-feeder/oracle/provider/provider.go
This brings the osmosis candle timestamp from seconds to milliseconds, which keeps it on par with all the other unix timestamps.
---
I have...
I have...
=> fix(price-feeder): fix osmosis timestamp

CHANGELOG.md, x/oracle/keeper/grpc_query.go, x/oracle/types/query.pb.gw.go
Simplifies the math for the oracle window progress query.
This was one of those things, "wait, why did I do it that way?"
---
I have...
I have...
=> refactor(oracle): simplify window progress query

go.mod, go.sum
https://github.com/dgrijalva/jwt-go is deprecated, not maintained and has security issue.
---
I have...
I have...
=> chore: migrate jwt-go dependency

contrib/scripts/protocgen.sh, proto/buf.gen.gogo.yaml
* Cleans up buf gogo config 
* Comment out `go mod tidy` from proto generator because it's not compatible with the Docker image we are using (it's still using go1.18) 
---
I have...
I have...
=> fix: proto generator

.golangci.yml
Use `unused` linter insead of `deadcode`, `varcheck` and `structcheck` which are abandoned.
---
I have...
I have...
=> chore: remove abandoned linters

proto/umee/oracle/v1/query.proto, swagger/swagger.yaml, x/oracle/types/query.pb.gw.go
Proto syntax fix and run `make proto-all`
Contents:
- Semicolon fix from #1311
- (unrelated) `make proto-gen` subtly changes `oracle/query.pb.gw.go`
- (unrelated) `make proto-swagger-gen` created a diff because `swagger/swagger.yaml` was out of date
=> chore: proto semicolon fix

CHANGELOG.md, x/oracle/client/cli/tx.go
Adds the option to override the validator address option for votes & prevotes.
This is required for addresses which have been delegated to by validators to vote via the CLI 🥳  
---
I have...
I have...
=> feat(oracle): validator address override option for cli prevotes & votes

CHANGELOG.md, x/leverage/client/cli/tx.go, x/leverage/client/tests/suite.go, x/leverage/client/tests/tests.go
closes: #1205
---
I have...
I have...
=> fix!: Use --from flag on all leverage CLI and remove first addr argument

x/leverage/client/tests/suite.go, x/leverage/client/tests/tests.go
I made these extra checks locally while investigating a `qa-integrations` issue. No bugs were found, but we may as well commit them.
=> test: add post-cleanup queries to leverage cli test

CHANGELOG.md, x/leverage/keeper/collateral.go
Quick bugfix to solve an issue we found in QA
`Collateral liquidity` was being interpteted as zero before any `collateral` was added (even with nonzero `liquidity`)
---
I have...
I have...
=> fix: Interpret x/0 collateral liquidity as 100%

CHANGELOG.md, x/leverage/keeper/filter.go, x/leverage/keeper/iter.go, x/leverage/keeper/reserves.go, x/leverage/keeper/validate.go
closes: #1223 
---
I have...
I have...
=> feat: automatically clear blacklisted collateral

.github/workflows/tests.yml
closes: #XXXX
---
I have...
I have...
=> ci: disable upgrade ci

CHANGELOG.md, app/app.go, app/upgrades.go
Fixes a chain halt on mainnet
```
ERR UPGRADE “v1.1.0” NEEDED at height: 3023282:
```
=> fix: add missing v1.1.0 upgrade handler

CHANGELOG.md, app/upgrades.go
v1.1.0 upgrade handler tries to run updates for modules. But none module registered an upgrade handler, causing panic.
---
I have...
I have...
=> fix: v1.1.0 handler

CHANGELOG.md, ante/fee.go
Gas feeder transactions, with increased gas adjustment, may go above 100k gas limit. For usability, we propose to increase the free gas from 100k to 140k.
I have...
=> feat: increase free oracle gas limit to 140k

proto/buf.lock
This reverts commit af5c6bbadfbae1d3ec28bbd49faa632bd0163f60.
Reverting https://github.com/umee-network/umee/pull/1397  -- was merged by mistake.
---
I have...
I have...
=> fix: revert: fix: buf cosmos-sdk version (#1397)

Makefile
`make proto-lint` doesn't work due to missing dependency in buf repository. 
References:
* https://github.com/umee-network/umee/pull/1397  (this PR was reverted)
This should be reverted in https://github.com/umee-network/umee/pull/1408, but now we need to progress.
=> fix: disable proto lint

CHANGELOG.md, proto/buf.lock, x/leverage/types/token.go
Fixes a copypasta in token validation that would allow us to set a parameter too high.
---
I have...
I have...
=> fix: MinCollateralLiquidity validation

.mergify.yml, README.md, price-feeder/CHANGELOG.md
Update price feeder docs for v1.0.0
---
I have...
I have...
=> docs: price-feeder v1.0.0

x/oracle/abci.go, x/oracle/keeper/reward.go, x/oracle/keeper/reward_test.go
Fixes RC1 Canon consensus failure.
Bug was in: https://github.com/umee-network/umee/pull/1433/files#diff-971aeedb004816fd5770d86dfa2d9ee39c5e53d7802773dd9e81cbc2cf890f62L60
---
I have...
I have...
=> fix: RewardBallotWinners determinism

app/app.go
This fixes the oracle endblocker issue seen where exchange rates aren't being set, introduced in #1434
This is happening because the endblocker for oracle is firing twice every voting period. First firing clears the votes, and the second clears the exchange rates and +1s the miss counters.
---
I have...
I have...
=> fix: oracle endblocker order fix

CHANGELOG.md, RELEASE_NOTES.md
Clarify Peggo instructions.
---
I have...
I have...
=> docs: update release notes

RELEASE_NOTES.md
=> docs: v3.0.1 release notes

.github/workflows/build.yml, .github/workflows/tests.yml, app/app.go
closes: #1308 
This pull request contains changes related improve cache of build-binary  github workflows , now github jobs will use cached binaries for testing the chain.
---
I have...
I have...
=> chore: improve cache build

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/binance.go, price-feeder/oracle/provider/kraken.go
closes: #1380 
---
I have...
I have...
=> refactor: Remove unnecessary instances of keepReconnecting

price-feeder/CHANGELOG.md, price-feeder/README.md, price-feeder/config/config.go, price-feeder/oracle/oracle.go, price-feeder/oracle/provider/crypto.go, price-feeder/oracle/provider/crypto_test.go, price-feeder/oracle/provider/provider.go
closes: #1305 
---
I have...
I have...
=> feat: Add crypto.com provider

proto/buf.lock, proto/buf.yaml
this pr will fix the `make proto-gen` , 
Note: 
**we need to update the commit for deps in buf config whenever  we bump the cosmos-sdk version** 
We can get the commits for deps of buf https://github.com/cosmos/cosmos-sdk/blob/v0.46.2/client/v2/internal/buf.lock
---
I have...
I have...
=> fix: update th buf cache to get proto deps

x/leverage/types/codec.go
=> fix: add new msg type to codec

umee.e2e.Dockerfile
Small fix regarding the e2e test , adding peggo binary to docker image
closes: #XXXX
---
I have...
I have...
=> fix: add peggo binary back to docker

price-feeder/oracle/provider/osmosisv2.go
The OsmosisV2 provider was unable to connect to our hosted server since it was using `ws` instead of `wss`. I was going to make this a config but I don't see needing to change this except when testing locally with just this provider.
---
I have...
I have...
=> fix(price-feeder): Update osmosisv2 wss scheme

util/bytes.go, util/bytes_test.go, x/oracle/keeper/historic_price.go, x/oracle/types/keys.go
Historical prices stored in the x/oracle module can collide. More specifically, if we have tokens where one denom is a prefix of another token denom (eg `ETH` and `ETHW`), then an iterator for `ETH` will also return prices for `ETHW` as well and calculate the prices totally wrong. This is obviously a bug.
---
I have...
I have...
=> fix(oracle): historical iterator

CHANGELOG.md, x/leverage/keeper/invariants.go, x/leverage/keeper/iter.go, x/leverage/keeper/store.go, x/leverage/keeper/token.go, x/leverage/types/keys.go, x/leverage/types/keys_test.go, x/oracle/keeper/historic_price.go, x/oracle/keeper/keeper.go, x/oracle/types/keys.go, x/oracle/types/keys_test.go
Follow up on https://github.com/umee-network/umee/pull/1573
Cleanup store key prefix functions.
---
I have...
I have...
=> chore!: refactore store key constructors

price-feeder/.goreleaser.yml, price-feeder/go.mod, price-feeder/go.sum
Fixes the price-feeder goreleaser by reverting changes in #1547 and removing `wasm` as a dependency by pegging the version of umeed to `v3.1.0`
addresses #1591 temporarily
---
I have...
I have...
=> fix: price feeder goreleaser

price-feeder/CHANGELOG.md, price-feeder/oracle/provider/osmosisv2.go
- Fixes only old candle prices in the price-feeder for the OsmosisV2 API
closes: [#87](https://github.com/umee-network/osmosis-api/issues/87)
---
I have...
I have...
=> fix(price-feeder): Parse multiple candles from OsmosisV2 response

price-feeder/oracle/util.go
This PR adds a minimum candle volume to the price feeder. 
This should assist with current issue on mainnet causing asset pairs to go down. Volume on Umee is zero for certain 5-minute time periods, making the price feeder unable to vote on the price of UMEE.
Due to this line of code, this causes downtime for all the other assets: 
https://github.com/umee-network/umee/blob/35a7d7dde4fb0ec34dbcf83fb5dd51e0f0159537/price-feeder/oracle/oracle.go#L268
This is addressed in https://github.com/umee-network/umee/pull/1635
---
I have...
your handle next to the items …
=> fix(price-feeder): add minimum candle volume

price-feeder/price-feeder.example.toml
TLDR; Removes unnecessary CRO & adds a 1.5 deviation threshold to wbtc.
Updates the price feeder config in response to a huobi API issue which cause validators to miss votes on mainnet. The huobi API seemed to be unable to respond to getting CRO data, which caused that asset to not have a price. Price feeders will stop voting if they do not have a price for every asset, but this is not good on mainnet. So, for now, we've removed CRO.
Example of mainnet price feeder logs: 
```
8:02AM DBG starting oracle tick module=oracle
8:02AM DBG executing oracle tick module=oracle
8:02AM ERR failed to get ticker prices from provider error="huobi failed to get ticker price for CROUSDT" module=oracle
8:02AM ERR oracle tick failed error="unable to get prices for all exchange candles" module=oracle
8:02AM …
```
=> chore: price-feeder config update

CHANGELOG.md, proto/umee/leverage/v1/query.proto, swagger/swagger.yaml, x/leverage/client/tests/tests.go, x/leverage/fixtures/token.go, x/leverage/keeper/grpc_query.go, x/leverage/keeper/grpc_query_test.go, x/leverage/keeper/iter_test.go, x/leverage/keeper/keeper.go, x/leverage/keeper/limits.go, x/leverage/keeper/liquidate.go, x/leverage/keeper/liquidate_test.go, x/leverage/keeper/msg_server_test.go, x/leverage/keeper/oracle.go, x/leverage/keeper/oracle_test.go, x/leverage/keeper/suite_test.go, x/leverage/keeper/token_test.go, x/leverage/simulation/operations_test.go, x/leverage/types/query.pb.go
Affects `QueryMarketSummary` for frontend as well as some leverage calculations internally. See changelog.
---
I have...
I have...
=> fix: increase price calc precision for high exponent assets

CHANGELOG.md, x/leverage/types/genesis.go
Conditions for bug:
- Starting chain from exported genesis (i.e. hard fork)
- Other genesis exports
Effects of bug:
- If we ever do a hard fork, reserves accumulated from borrow interest would not carry over.
- Other processes relying on exported genesis might arrive at a bad app hash due to disagreeing on state
This would essentially making it as if the `reserve_factor` had been zero instead of `~0.1` for all tokens:
- slightly benefitting suppliers
- but putting protocol bad debt repayment at risk
---
I have...
your handle next to the items reviewed if you only …
=> fix: export genesis tracks reserves

CHANGELOG.md, x/leverage/types/codec.go
This is required for ledger signing - and for our Kepler integration, which uses amino (for all users) to support ledgers.
=> fix: add amino support for MsgMaxWithdraw

tests/e2e/e2e_test.go, tests/grpc/historical.go, tests/grpc/price_store.go
- Fixed the flakiness of the historical e2e grpc tests by ensuring that the collection of prices starts at the beginning of a median period
- Updated the price store to include prices for all denoms; effectively checking all medians in parallel
- Actively check for existing exchange rates instead of waiting an arbitrary number of blocks
---
I have...
I have...
=> ci(tests): fix historical e2e flaky test

tests/e2e/e2e_setup_test.go, tests/grpc/price_listener.go, x/oracle/abci.go, x/oracle/abci_test.go, x/oracle/keeper/grpc_query.go, x/oracle/keeper/grpc_query_test.go, x/oracle/keeper/historic_price.go, x/oracle/types/price.go
- Update pruning for historic stamps, medians, and median deviations to prune all prices older than a specific block instead of only pruning one price at a time.
- Remove `VotePeriod` from the pruning block calculations
- Sort the query output for median and median deviations by block and then denom
Fixes no medians or median deviations being pruned
=> fix(oracle): Update price pruning

CHANGELOG.md, x/oracle/keeper/hooks.go, x/oracle/keeper/hooks_test.go
This was the source of the reappearance of `CRO` and `ETH2` on the canon-2 testnet recently.
=> fix: oracle accept list no longer automatically adds blacklisted tokens

util/error.go, x/leverage/abci.go, x/leverage/keeper/genesis.go, x/leverage/keeper/iter.go, x/leverage/keeper/store.go, x/oracle/genesis.go, x/oracle/keeper/slash.go, x/oracle/module.go, x/uibc/module/abci.go, x/uibc/module/module.go, x/uibc/quota/keeper/genesis.go
Simplify the "if err -> panic" code flows.
---
I have...
I have...
=> chore: adding calls to util.Panic

app/app.go, x/uibc/quota/ibc_module.go
Updates related to the ICS20 middleware research and audit.
+ fix related to acknowledgment error deserialization.
---
I have...
I have...
=> fix: correct ICS20 middleware handlers

tests/e2e/e2e_setup_test.go
2e2 price feeder test is flaky - probably the timeout is too small.
Increasing from 1min to 1:30min
---
I have...
I have...
=> fix: increase pricefeeder e2e test timeout

app/upgrades.go, util/checkers/proposal.go, x/incentive/errors.go, x/incentive/msgs.go, x/leverage/keeper/exchange_rate.go, x/leverage/keeper/keeper.go, x/leverage/keeper/oracle.go, x/leverage/keeper/token.go, x/leverage/types/errors.go, x/leverage/types/genesis.go, x/leverage/types/msgs.go, x/leverage/types/token.go, x/oracle/keeper/historic_price.go, x/oracle/keeper/keeper.go, x/oracle/keeper/msg_server.go, x/oracle/types/errors.go, x/oracle/types/msgs.go, x/oracle/types/msgs_test.go, x/uibc/errors.go, x/uibc/ics20/keeper/keeper.go, x/uibc/msg.go, x/uibc/quota/ibc_module.go, x/uibc/quota/keeper/quota.go, x/uibc/quota/keeper/relay.go
Fixes golangci-lint complains about usage of deprecated function
=> fix: deprecated use of sdkerrors

app/upgrades.go
reuse `onlyModuleMigrations` in upgrade handler.
=> chore: simplify upgrades

CHANGELOG.md, x/leverage/keeper/collateral.go, x/leverage/keeper/msg_server_test.go, x/leverage/keeper/oracle_test.go, x/leverage/keeper/suite_test.go, x/leverage/types/expected_types.go
When some token prices are missing from the oracle, it becomes impossible to calculate a token's collateral share.
However, if the collateralized token's price is known, and enough other token prices are known to prove that it cannot possibly be over its `MaxCollateralShare`, then we can let `MsgSupplyCollateral` or `MsgCollateralize` succeed anyway.
=> fix: collateral share restriction works during partial price outages

app/upgrades.go, x/leverage/keeper/migrations.go, x/leverage/types/errors.go, x/oracle/keeper/migrations.go
Logs error in case there is a supply rather then failing the migration.
---
I have...
I have...
=> fix: bnb migration

x/leverage/keeper/migrations.go
If the BNB denom is not present in the leverage registry, skips the BNB migration instead of causing an error.
This shouldn't affect mainnet or `canon-2`, but is good form in case we ever run this migration on a different testnet.
=> fix: skip BNB migration instead of error if no BNB denom present

CHANGELOG.md, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go, x/oracle/abci.go, x/oracle/abci_test.go
=> fix: getting bonded validator power in oracle endblocker

app/upgrades.go
In last two upgrades we had / have a sequence of rc releases, each of which is a breaking change, and require new upgrade handler. This is not relevant to the mainnet. Instead I propose:
1. Use `betaX` rather than `rcX`.
1. keep single handler and rename until we have successful, stable RC
=> chore: update upgrades structure

price-feeder/price-feeder.example.toml, price-feeder/tests/integration/provider_test.go
- Add WAXL, DOT, and MATIC to example config
--- PASS: TestServiceTestSuite (120.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders (0.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/huobi (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/osmosisv2 (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/mexc (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/kraken (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/okx (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/crypto (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/gate (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/coinbase (60.00s)
--- PASS: TestServiceTestSuite/TestWebsocketProviders/binanceus (60.00s)
--- PASS: …
=> chore: Add WAXL, DOT, and MATIC to example config

tests/e2e/e2e_util_test.go
`else` inherits value from the `if` , so `valPtr` will be `nil` there.
=> fix: e2e interface assertion

.codecov.yml, x/incentive/keys.go, x/incentive/keys_test.go, x/incentive/params_test.go
We were including `pb.gw.go` files in our coverage.
Note that I had to add some code changes to trigger the coverage report, so I grabbed some trivial ones with tests from an incentive module PR.
=> fix: codecov file types

codecov.yml, util/bytes.go
* removed `app` as a separate target - we can keep it in `project`
* still we need to verify if the client metric is correct there... sounds off that we currently meeting 99% there.
=> chore: set codecov targets

CHANGELOG.md, app/app.go, app/upgrades.go
* Integrates IBC ICA Host stack.
* also added few comments for IBC fee integration for the future.
=> feat: integrate ICA

CHANGELOG.md, x/leverage/keeper/genesis.go, x/leverage/keeper/genesis_test.go
closes: #XXXX
---
I have...
I have...
=> fix: genesis type cast

CHANGELOG.md, x/uibc/ics20/keeper/keeper.go, x/uibc/quota/keeper/genesis.go, x/uibc/quota/keeper/grpc_query.go, x/uibc/quota/keeper/keeper_test.go, x/uibc/quota/keeper/mocks_test.go, x/uibc/quota/keeper/quota.go, x/uibc/quota/keeper/quota_test.go, x/uibc/quota/keeper/quota_unit_test.go, x/uibc/quota/keeper/unit_test.go
* adding missing quota params check for unlimited transfers
* adding unit tests.
=> feat: quota zero check

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/simulations.yml, .github/workflows/tests.yml, CHANGELOG.md
trying to optimize the merge queue. I found that Super linter checks are performed by the merge queue, while other checks are correctly cashed and not executed.
=> perf: linter merge queue workflow

CHANGELOG.md, x/leverage/keeper/msg_server.go, x/leverage/keeper/msg_server_test.go, x/leverage/keeper/token.go
closes: #1883 
---
I have...
I have...
=> chore: add checks for duplicate symbol denoms for adding new tokens on leverage

CHANGELOG.md, go.mod, go.sum
This also adds the config to disable colored logs.
=> chore: bump Cosmos SDK to 0.46.12

util/store/store.go, util/store/unmarshal.go
Using generics to set the value and get the value in store/utils 
closes: #1870 
---
I have...
I have...
=> chore: use generics for set and get value in store util

CHANGELOG.md, tests/e2e/e2e_ibc_test.go, x/uibc/ics20/ibc_module.go, x/uibc/quota/ibc_module.go, x/uibc/quota/keeper/ics4_wrapper.go, x/uibc/quota/keeper/quota.go
Temporary disable inflow quota
=> feat: disable inflow quota

app/upgrades.go
Added an util function to simplify upgrade registration even more.
=> feat: better upgrade registration

.github/workflows/tests.yml
cache is not reused in other actions, and adding it increases the setup time.
=> chore: speedup e2e by removing docker cache

app/app.go, app/upgrades.go
closes: #XXXX
---
I have...
I have...
=> chore: add wasm to upgrade handler v4.5

go.mod, go.sum
This PR takes the exact commit of wasmd that umee was using, and applies the wasmvm patch to it.  It should not be 
state breaking. 
---
I have...
prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
I have...
=> fix: bump wasmvm upstream

go.mod, go.sum
closes: #XXXX
---
I have...
I have...
=> chore: bump ibc-go

CHANGELOG.md, README.md, RELEASE_NOTES.md, app/app.go, go.mod, go.sum
+ bumps GB version
+ set Burn mechanism to true
=> bump GB and set GB burn

app/app.go, docs/cosmwasm.md
closes: #XXXX
---
I have...
I have...
=> docs: docs for cosmwasm native module queries and msgs

CHANGELOG.md, x/leverage/keeper/msg_server.go
closes: #XXXX
---
I have...
I have...
=> fix: MsgSupplyCollateral and MinCollateralLiquidity

CHANGELOG.md, app/app.go, app/inflation/expected_keepers.go, app/inflation/inflatin.go
Adding cusotmized `InflationCalculationFn` and a inflation `Calculator` type.
Should be used in https://github.com/umee-network/umee/pull/2145 to avoid module fork.
---
I have...
I have...
=> feat: mint calculator

x/incentive/client/cli/query.go, x/incentive/client/cli/tx.go, x/incentive/client/tests/tests.go, x/leverage/client/cli/query.go, x/leverage/client/cli/tx.go, x/leverage/client/tests/tests.go, x/metoken/client/cli/query.go, x/metoken/client/cli/tx.go, x/metoken/client/tests/tests.go, x/oracle/client/cli/query.go, x/oracle/client/cli/tx.go, x/oracle/client/tests/suite.go, x/uibc/client/cli/query.go, x/uibc/client/tests/query_test.go
closes: #2039 
Removes `GetCmd` prefix from cli commands' builders
=> style: remove prefix `GetCmd` from cli

.github/workflows/govulncheck.yml, CHANGELOG.md, x/leverage/keeper/liquidate.go, x/leverage/keeper/liquidate_test.go
This wasn't the bug we encountered, but it is one that could happen
=> fix leveraged liquidate not working during low liquidity

CHANGELOG.md, RELEASE_NOTES.md, app/upgrades.go
As per Amulet team analysis, the existing 21MB block size may expose security risk and teams should consider reducing it. In this PR we reduce it to 4 MB, giving enough room for Cosmowasm deployments and big transactions. Blocks full of oracle txs are less than 40kB.
=> chore: change consensus.block.max_size to 4 MB

app/wasm/query/handle_metoken.go, app/wasm/query/plugin.go, app/wasm/query/types.go, app/wasm/test/umee_cw_test.go
closes: #XXXX
---
I have...
I have...
=> tests: metoken wasm stargate queries

go.mod, go.sum
Fix: remove replace which was outdated and add fix the keyring dependency.
=> fix: go-schnorrkel and keyring dependencies

app/app.go, x/auction/keeper/keeper.go, x/leverage/keeper/internal_test.go, x/leverage/keeper/keeper.go, x/metoken/keeper/intest/keeper_test.go, x/metoken/keeper/intest/msg_server_test.go, x/metoken/keeper/keeper.go, x/metoken/keeper/unit_test.go
=> fix(auction) link rewards accounts

x/leverage/keeper/accounts_summary.go
We miss the account summary when user collateralize the uTokens
---
I have...
I have...
=> fix: fix the account summary grpc

Makefile, x/auction/keeper/rewards.go
closes: #XXXX
---
I have...
I have...
=> fix: fix the auction creation in every end block

CHANGELOG.md, README.md, RELEASE_NOTES.md
update the readme, changelog and release notes
---
I have...
I have...
=> docs: update the readme and changelog and release notes

RELEASE_NOTES.md, app/upgrades.go
fix the upgrade name
---
I have...
I have...
=> chore: change the upgrade name from v6.7-rc1 to v6.7.0-rc1

app/upgrades.go
closes: #XXXX
---
I have...
I have...
=> fix: fix the canon 4 upgrade
